-- Requires extension pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Generated by airtable_export_to_postgres_sql_v3.js
-- 2026-02-01T15:50:02.915Z
BEGIN;
CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE IF NOT EXISTS "public"."strains" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "strain_id" text,
  "species_strain" text,
  "regulated" boolean
);

CREATE TABLE IF NOT EXISTS "public"."recipes" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "recipe_id" text,
  "name" text,
  "category" text,
  "ingredients" text,
  "notes" text
);

CREATE TABLE IF NOT EXISTS "public"."products" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "product_id" text,
  "name_mat" text,
  "item_category_mat" text,
  "net_weight_g" numeric,
  "net_weight_oz" numeric,
  "net_volume_ml" numeric,
  "pack_date" date,
  "use_by" date,
  "package_size_g" numeric,
  "package_count" numeric,
  "action" text,
  "origin_lot_ids_json" text,
  "ui_error" text,
  "ui_error_at" timestamp without time zone,
  "tray_state" text,
  "notes" text
);

CREATE TABLE IF NOT EXISTS "public"."lots" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "lot_id" text,
  "item_name_mat" text,
  "qty" numeric,
  "unit_size" numeric,
  "status" text,
  "parents_json" text,
  "operator" text,
  "created_at" timestamp without time zone,
  "use_by" date,
  "action" text,
  "item_category_mat" text,
  "process_type_mat" text,
  "strain_species_strain_mat" text,
  "vendor_name_mat" text,
  "lc_volume_ml" numeric,
  "output_count" numeric,
  "fruiting_goal" text,
  "flush_no" numeric,
  "harvest_weight_g" numeric,
  "notes" text,
  "syringe_count" numeric,
  "source_type" text,
  "vendor_name" text,
  "vendor_batch" text,
  "received_date" date,
  "total_volume_ml" numeric,
  "ui_error" text,
  "ui_error_at" timestamp without time zone,
  "remaining_volume_ml" numeric,
  "fresh_tray_count" numeric,
  "frozen_tray_count" numeric,
  "casing_applied_at" timestamp without time zone,
  "casing_notes" text,
  "casing_qty_used_g" numeric,
  "label_template" text,
  "override_inoc_time" timestamp without time zone,
  "inoculated_at" timestamp without time zone,
  "override_spawn_time" timestamp without time zone,
  "spawned_at" timestamp without time zone,
  "sterilized_at" timestamp without time zone,
  "plate_count" numeric,
  "plate_group_id" text
);

CREATE TABLE IF NOT EXISTS "public"."items" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "item_id" text,
  "name" text,
  "category" text,
  "default_unit_size_lb" numeric,
  "default_unit_size_ml" numeric,
  "default_unit_size_oz" numeric,
  "default_unit_size_g" numeric,
  "default_unit_size" text
);

CREATE TABLE IF NOT EXISTS "public"."events" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "event_id" text,
  "type" text,
  "timestamp" timestamp without time zone,
  "operator" text,
  "station" text,
  "fields_json" text,
  "lots" text
);

CREATE TABLE IF NOT EXISTS "public"."locations" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "name" text,
  "type" text,
  "notes" text
);

CREATE TABLE IF NOT EXISTS "public"."sterilization_runs" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "steri_run_id" text,
  "start_time" timestamp without time zone,
  "end_time" timestamp without time zone,
  "operator" text,
  "planned_count" numeric,
  "good_count" numeric,
  "destroyed_count" numeric,
  "planned_unit_size" numeric,
  "ui_error" text,
  "ui_error_at" timestamp without time zone,
  "process_type" text,
  "target_temp_c" numeric,
  "pressure_mode" text,
  "override_end_time" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS "public"."print_queue" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "print_id" text,
  "source_kind" text,
  "print_status" text,
  "label_type" text,
  "error_msg" text,
  "created_at" timestamp without time zone,
  "claimed_by" text,
  "claimed_at" timestamp without time zone,
  "printed_by" text,
  "printed_at" timestamp without time zone,
  "pdf_path" text
);

CREATE TABLE IF NOT EXISTS "public"."ecommerce" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "name" text,
  "status" text,
  "ecwid_sku" text,
  "sync_to_ecwid" boolean,
  "notes" text,
  "ecwid_category" text,
  "ecwid_price" numeric,
  "ecwid_stock" numeric,
  "ecwid_url" text,
  "ecwid_image" jsonb
);

CREATE TABLE IF NOT EXISTS "public"."ecommerce_orders" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now(),
  "name" text,
  "ecwid_order_id" text,
  "order_number" numeric,
  "status" text,
  "order_date" timestamp without time zone,
  "customer_name" text,
  "customer_email" text,
  "items_json" text,
  "ecwid_skus" text
);

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_products"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."product_id" IS NULL OR NEW."product_id" = '' THEN
    NEW."product_id" := (('PROD-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_products" ON "public"."products";
CREATE TRIGGER "set_autogen_ids_products" BEFORE INSERT OR UPDATE ON "public"."products"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_products"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_lots"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."lot_id" IS NULL OR NEW."lot_id" = '' THEN
    NEW."lot_id" := (('LOT-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_lots" ON "public"."lots";
CREATE TRIGGER "set_autogen_ids_lots" BEFORE INSERT OR UPDATE ON "public"."lots"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_lots"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_events"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."event_id" IS NULL OR NEW."event_id" = '' THEN
    NEW."event_id" := (('EVENT-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_events" ON "public"."events";
CREATE TRIGGER "set_autogen_ids_events" BEFORE INSERT OR UPDATE ON "public"."events"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_events"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_sterilization_runs"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."steri_run_id" IS NULL OR NEW."steri_run_id" = '' THEN
    NEW."steri_run_id" := (('RUN-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_sterilization_runs" ON "public"."sterilization_runs";
CREATE TRIGGER "set_autogen_ids_sterilization_runs" BEFORE INSERT OR UPDATE ON "public"."sterilization_runs"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_sterilization_runs"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_print_queue"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."print_id" IS NULL OR NEW."print_id" = '' THEN
    NEW."print_id" := (('PRINT-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_print_queue" ON "public"."print_queue";
CREATE TRIGGER "set_autogen_ids_print_queue" BEFORE INSERT OR UPDATE ON "public"."print_queue"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_print_queue"();
COMMIT;
