-- Requires extension pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Generated by airtable_export_to_postgres_sql.js
-- 2026-02-13T21:25:35.818Z
SET client_min_messages TO WARNING;
BEGIN;
CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE IF NOT EXISTS "public"."strains" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "strain_id" text,
  "species_strain" text,
  "regulated" boolean,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_strains_strain_id'
            AND c.conrelid = 'public.strains'::regclass
        ) THEN
          ALTER TABLE "public"."strains"
            ADD CONSTRAINT "uq_strains_strain_id" UNIQUE ("strain_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."recipes" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "recipe_id" text,
  "name" text,
  "category" text,
  "ingredients" text,
  "notes" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_recipes_recipe_id'
            AND c.conrelid = 'public.recipes'::regclass
        ) THEN
          ALTER TABLE "public"."recipes"
            ADD CONSTRAINT "uq_recipes_recipe_id" UNIQUE ("recipe_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."products" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "product_id" text,
  "item_id" bigint,
  "name_mat" text,
  "item_category_mat" text,
  "net_weight_g" numeric,
  "net_weight_oz" numeric,
  "net_volume_ml" numeric,
  "pack_date" date,
  "use_by" date,
  "package_item_id" bigint,
  "package_size_g" numeric,
  "package_count" numeric,
  "storage_location_id" bigint,
  "action" text,
  "origin_lot_ids_json" text,
  "strain_id" bigint,
  "ui_error" text,
  "ui_error_at" timestamp without time zone,
  "tray_state" text,
  "notes" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_products_product_id'
            AND c.conrelid = 'public.products'::regclass
        ) THEN
          ALTER TABLE "public"."products"
            ADD CONSTRAINT "uq_products_product_id" UNIQUE ("product_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."lots" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "lot_id" text,
  "item_id" bigint,
  "item_name_mat" text,
  "recipe_id" bigint,
  "strain_id" bigint,
  "qty" numeric,
  "unit_size" numeric,
  "status" text,
  "parents_json" text,
  "steri_run_id" bigint,
  "location_id" bigint,
  "operator" text,
  "created_at" timestamp without time zone,
  "use_by" date,
  "action" text,
  "item_category_mat" text,
  "process_type_mat" text,
  "strain_species_strain_mat" text,
  "vendor_name_mat" text,
  "lc_volume_ml" numeric,
  "output_count" numeric,
  "fruiting_goal" text,
  "flush_no" numeric,
  "harvest_weight_g" numeric,
  "notes" text,
  "syringe_count" numeric,
  "syringe_item_id" bigint,
  "source_type" text,
  "vendor_name" text,
  "vendor_batch" text,
  "received_date" date,
  "total_volume_ml" numeric,
  "ui_error" text,
  "ui_error_at" timestamp without time zone,
  "remaining_volume_ml" numeric,
  "fresh_tray_count" numeric,
  "frozen_tray_count" numeric,
  "casing_lot_id" bigint,
  "casing_applied_at" timestamp without time zone,
  "casing_notes" text,
  "casing_qty_used_g" numeric,
  "label_template" text,
  "override_inoc_time" timestamp without time zone,
  "inoculated_at" timestamp without time zone,
  "override_spawn_time" timestamp without time zone,
  "spawned_at" timestamp without time zone,
  "sterilized_at" timestamp without time zone,
  "source_lot_id" bigint,
  "plate_count" numeric,
  "plate_group_id" text,
  "parent_lot_id" bigint,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_lots_lot_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "uq_lots_lot_id" UNIQUE ("lot_id");
        END IF;
      END $$;
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_lots_plate_group_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "uq_lots_plate_group_id" UNIQUE ("plate_group_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."items" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "item_id" text,
  "name" text,
  "category" text,
  "default_unit_size_lb" numeric,
  "default_unit_size_ml" numeric,
  "default_unit_size_oz" numeric,
  "default_unit_size_g" numeric,
  "default_unit_size" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_items_item_id'
            AND c.conrelid = 'public.items'::regclass
        ) THEN
          ALTER TABLE "public"."items"
            ADD CONSTRAINT "uq_items_item_id" UNIQUE ("item_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."events" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "event_id" text,
  "lot_id" bigint,
  "product_id" bigint,
  "type" text,
  "timestamp" timestamp without time zone,
  "operator" text,
  "station" text,
  "fields_json" text,
  "lots" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_events_event_id'
            AND c.conrelid = 'public.events'::regclass
        ) THEN
          ALTER TABLE "public"."events"
            ADD CONSTRAINT "uq_events_event_id" UNIQUE ("event_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."locations" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "name" text,
  "type" text,
  "notes" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_locations_name" ON "public"."locations"("name");

CREATE TABLE IF NOT EXISTS "public"."sterilization_runs" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "steri_run_id" text,
  "planned_item_id" bigint,
  "start_time" timestamp without time zone,
  "end_time" timestamp without time zone,
  "operator" text,
  "planned_recipe_id" bigint,
  "planned_count" numeric,
  "good_count" numeric,
  "destroyed_count" numeric,
  "planned_unit_size" numeric,
  "ui_error" text,
  "ui_error_at" timestamp without time zone,
  "process_type" text,
  "target_temp_c" numeric,
  "pressure_mode" text,
  "override_end_time" timestamp without time zone,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_sterilization_runs_steri_run_id'
            AND c.conrelid = 'public.sterilization_runs'::regclass
        ) THEN
          ALTER TABLE "public"."sterilization_runs"
            ADD CONSTRAINT "uq_sterilization_runs_steri_run_id" UNIQUE ("steri_run_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."print_queue" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "print_id" text,
  "source_kind" text,
  "lot_id" bigint,
  "product_id" bigint,
  "print_status" text,
  "label_type" text,
  "error_msg" text,
  "created_at" timestamp without time zone,
  "run_id" bigint,
  "claimed_by" text,
  "claimed_at" timestamp without time zone,
  "printed_by" text,
  "printed_at" timestamp without time zone,
  "pdf_path" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_print_queue_print_id'
            AND c.conrelid = 'public.print_queue'::regclass
        ) THEN
          ALTER TABLE "public"."print_queue"
            ADD CONSTRAINT "uq_print_queue_print_id" UNIQUE ("print_id");
        END IF;
      END $$;

CREATE TABLE IF NOT EXISTS "public"."ecommerce" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "name" text,
  "item_id" bigint,
  "strain_id" bigint,
  "status" text,
  "ecwid_sku" text,
  "sync_to_ecwid" boolean,
  "notes" text,
  "ecwid_category" text,
  "ecwid_price" numeric,
  "ecwid_stock" numeric,
  "ecwid_url" text,
  "ecwid_image" jsonb,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_ecommerce_name" ON "public"."ecommerce"("name");

CREATE TABLE IF NOT EXISTS "public"."ecommerce_orders" (
  "nocopk" BIGSERIAL PRIMARY KEY,
  "name" text,
  "ecwid_order_id" text,
  "order_number" numeric,
  "status" text,
  "order_date" timestamp without time zone,
  "customer_name" text,
  "customer_email" text,
  "items_json" text,
  "ecwid_skus" text,
  "nocouuid" uuid DEFAULT gen_random_uuid(),
  "airtable_id" text UNIQUE,
  "nc_created_at" timestamp without time zone DEFAULT now(),
  "nc_updated_at" timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_ecommerce_orders_name" ON "public"."ecommerce_orders"("name");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'uq_ecommerce_orders_ecwid_order_id'
            AND c.conrelid = 'public.ecommerce_orders'::regclass
        ) THEN
          ALTER TABLE "public"."ecommerce_orders"
            ADD CONSTRAINT "uq_ecommerce_orders_ecwid_order_id" UNIQUE ("ecwid_order_id");
        END IF;
      END $$;

-- Deferred FK constraints for canonical single-link columns
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_products_item_id'
            AND c.conrelid = 'public.products'::regclass
        ) THEN
          ALTER TABLE "public"."products"
            ADD CONSTRAINT "fk_products_item_id"
            FOREIGN KEY ("item_id")
            REFERENCES "public"."items"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_products_item_id" ON "public"."products"("item_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_products_package_item_id'
            AND c.conrelid = 'public.products'::regclass
        ) THEN
          ALTER TABLE "public"."products"
            ADD CONSTRAINT "fk_products_package_item_id"
            FOREIGN KEY ("package_item_id")
            REFERENCES "public"."items"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_products_package_item_id" ON "public"."products"("package_item_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_products_storage_location_id'
            AND c.conrelid = 'public.products'::regclass
        ) THEN
          ALTER TABLE "public"."products"
            ADD CONSTRAINT "fk_products_storage_location_id"
            FOREIGN KEY ("storage_location_id")
            REFERENCES "public"."locations"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_products_storage_location_id" ON "public"."products"("storage_location_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_products_strain_id'
            AND c.conrelid = 'public.products'::regclass
        ) THEN
          ALTER TABLE "public"."products"
            ADD CONSTRAINT "fk_products_strain_id"
            FOREIGN KEY ("strain_id")
            REFERENCES "public"."strains"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_products_strain_id" ON "public"."products"("strain_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_item_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_item_id"
            FOREIGN KEY ("item_id")
            REFERENCES "public"."items"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_item_id" ON "public"."lots"("item_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_recipe_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_recipe_id"
            FOREIGN KEY ("recipe_id")
            REFERENCES "public"."recipes"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_recipe_id" ON "public"."lots"("recipe_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_strain_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_strain_id"
            FOREIGN KEY ("strain_id")
            REFERENCES "public"."strains"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_strain_id" ON "public"."lots"("strain_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_steri_run_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_steri_run_id"
            FOREIGN KEY ("steri_run_id")
            REFERENCES "public"."sterilization_runs"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_steri_run_id" ON "public"."lots"("steri_run_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_location_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_location_id"
            FOREIGN KEY ("location_id")
            REFERENCES "public"."locations"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_location_id" ON "public"."lots"("location_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_syringe_item_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_syringe_item_id"
            FOREIGN KEY ("syringe_item_id")
            REFERENCES "public"."items"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_syringe_item_id" ON "public"."lots"("syringe_item_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_casing_lot_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_casing_lot_id"
            FOREIGN KEY ("casing_lot_id")
            REFERENCES "public"."lots"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_casing_lot_id" ON "public"."lots"("casing_lot_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_source_lot_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_source_lot_id"
            FOREIGN KEY ("source_lot_id")
            REFERENCES "public"."lots"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_source_lot_id" ON "public"."lots"("source_lot_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_lots_parent_lot_id'
            AND c.conrelid = 'public.lots'::regclass
        ) THEN
          ALTER TABLE "public"."lots"
            ADD CONSTRAINT "fk_lots_parent_lot_id"
            FOREIGN KEY ("parent_lot_id")
            REFERENCES "public"."lots"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_lots_parent_lot_id" ON "public"."lots"("parent_lot_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_events_lot_id'
            AND c.conrelid = 'public.events'::regclass
        ) THEN
          ALTER TABLE "public"."events"
            ADD CONSTRAINT "fk_events_lot_id"
            FOREIGN KEY ("lot_id")
            REFERENCES "public"."lots"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_events_lot_id" ON "public"."events"("lot_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_events_product_id'
            AND c.conrelid = 'public.events'::regclass
        ) THEN
          ALTER TABLE "public"."events"
            ADD CONSTRAINT "fk_events_product_id"
            FOREIGN KEY ("product_id")
            REFERENCES "public"."products"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_events_product_id" ON "public"."events"("product_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_sterilization_runs_planned_item_id'
            AND c.conrelid = 'public.sterilization_runs'::regclass
        ) THEN
          ALTER TABLE "public"."sterilization_runs"
            ADD CONSTRAINT "fk_sterilization_runs_planned_item_id"
            FOREIGN KEY ("planned_item_id")
            REFERENCES "public"."items"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_sterilization_runs_planned_item_id" ON "public"."sterilization_runs"("planned_item_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_sterilization_runs_planned_recipe_id'
            AND c.conrelid = 'public.sterilization_runs'::regclass
        ) THEN
          ALTER TABLE "public"."sterilization_runs"
            ADD CONSTRAINT "fk_sterilization_runs_planned_recipe_id"
            FOREIGN KEY ("planned_recipe_id")
            REFERENCES "public"."recipes"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_sterilization_runs_planned_recipe_id" ON "public"."sterilization_runs"("planned_recipe_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_print_queue_lot_id'
            AND c.conrelid = 'public.print_queue'::regclass
        ) THEN
          ALTER TABLE "public"."print_queue"
            ADD CONSTRAINT "fk_print_queue_lot_id"
            FOREIGN KEY ("lot_id")
            REFERENCES "public"."lots"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_print_queue_lot_id" ON "public"."print_queue"("lot_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_print_queue_product_id'
            AND c.conrelid = 'public.print_queue'::regclass
        ) THEN
          ALTER TABLE "public"."print_queue"
            ADD CONSTRAINT "fk_print_queue_product_id"
            FOREIGN KEY ("product_id")
            REFERENCES "public"."products"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_print_queue_product_id" ON "public"."print_queue"("product_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_print_queue_run_id'
            AND c.conrelid = 'public.print_queue'::regclass
        ) THEN
          ALTER TABLE "public"."print_queue"
            ADD CONSTRAINT "fk_print_queue_run_id"
            FOREIGN KEY ("run_id")
            REFERENCES "public"."sterilization_runs"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_print_queue_run_id" ON "public"."print_queue"("run_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_ecommerce_item_id'
            AND c.conrelid = 'public.ecommerce'::regclass
        ) THEN
          ALTER TABLE "public"."ecommerce"
            ADD CONSTRAINT "fk_ecommerce_item_id"
            FOREIGN KEY ("item_id")
            REFERENCES "public"."items"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_ecommerce_item_id" ON "public"."ecommerce"("item_id");
DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conname = 'fk_ecommerce_strain_id'
            AND c.conrelid = 'public.ecommerce'::regclass
        ) THEN
          ALTER TABLE "public"."ecommerce"
            ADD CONSTRAINT "fk_ecommerce_strain_id"
            FOREIGN KEY ("strain_id")
            REFERENCES "public"."strains"("nocopk")
            DEFERRABLE INITIALLY DEFERRED;
        END IF;
      END $$;
CREATE INDEX IF NOT EXISTS "ix_ecommerce_strain_id" ON "public"."ecommerce"("strain_id");

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_products"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."product_id" IS NULL OR NEW."product_id" = '' THEN
    NEW."product_id" := (('PROD-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_products" ON "public"."products";
CREATE TRIGGER "set_autogen_ids_products" BEFORE INSERT OR UPDATE ON "public"."products"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_products"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_lots"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."lot_id" IS NULL OR NEW."lot_id" = '' THEN
    NEW."lot_id" := (('LOT-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_lots" ON "public"."lots";
CREATE TRIGGER "set_autogen_ids_lots" BEFORE INSERT OR UPDATE ON "public"."lots"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_lots"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_events"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."event_id" IS NULL OR NEW."event_id" = '' THEN
    NEW."event_id" := (('EVENT-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_events" ON "public"."events";
CREATE TRIGGER "set_autogen_ids_events" BEFORE INSERT OR UPDATE ON "public"."events"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_events"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_sterilization_runs"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."steri_run_id" IS NULL OR NEW."steri_run_id" = '' THEN
    NEW."steri_run_id" := (('RUN-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_sterilization_runs" ON "public"."sterilization_runs";
CREATE TRIGGER "set_autogen_ids_sterilization_runs" BEFORE INSERT OR UPDATE ON "public"."sterilization_runs"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_sterilization_runs"();

CREATE OR REPLACE FUNCTION "public"."set_autogen_ids_print_queue"() RETURNS trigger AS $$
BEGIN
  IF NEW."nocouuid" IS NULL THEN NEW."nocouuid" := gen_random_uuid(); END IF;
  IF NEW."nc_created_at" IS NULL THEN NEW."nc_created_at" := now(); END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW."nc_updated_at" := now();
  END IF;
  IF NEW."print_id" IS NULL OR NEW."print_id" = '' THEN
    NEW."print_id" := (('PRINT-') || to_char((NEW."nc_created_at")::timestamp, 'YYMMDD') || '-' || right(COALESCE(NULLIF(NEW."airtable_id"::text,''), replace(NEW."nocouuid"::text,'-',''), NEW."nocopk"::text), 4));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "set_autogen_ids_print_queue" ON "public"."print_queue";
CREATE TRIGGER "set_autogen_ids_print_queue" BEFORE INSERT OR UPDATE ON "public"."print_queue"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_autogen_ids_print_queue"();
COMMIT;
