-- Generated by airtable_export_to_postgres_sql_v3.js
-- 2026-01-27T15:48:34.522Z
BEGIN;

CREATE TABLE IF NOT EXISTS "public"."_m2m_strains_lots_lots" (
  "strains_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_strains_lots_lots_strains_id_idx" ON "public"."_m2m_strains_lots_lots"("strains_id");
CREATE INDEX IF NOT EXISTS "_m2m_strains_lots_lots_lots_id_idx" ON "public"."_m2m_strains_lots_lots"("lots_id");
ALTER TABLE "public"."_m2m_strains_lots_lots"
  ADD CONSTRAINT "_m2m_strains_lots_lots_strains_id_fk" FOREIGN KEY ("strains_id") REFERENCES "public"."strains"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_strains_lots_lots"
  ADD CONSTRAINT "_m2m_strains_lots_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_strains_ecommerce_ecommerce" (
  "strains_id" bigint NOT NULL,
  "ecommerce_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_strains_ecommerce_ecommerce_strains_id_idx" ON "public"."_m2m_strains_ecommerce_ecommerce"("strains_id");
CREATE INDEX IF NOT EXISTS "_m2m_strains_ecommerce_ecommerce_ecommerce_id_idx" ON "public"."_m2m_strains_ecommerce_ecommerce"("ecommerce_id");
ALTER TABLE "public"."_m2m_strains_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_strains_ecommerce_ecommerce_strains_id_fk" FOREIGN KEY ("strains_id") REFERENCES "public"."strains"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_strains_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_strains_ecommerce_ecommerce_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_strains_products_products" (
  "strains_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_strains_products_products_strains_id_idx" ON "public"."_m2m_strains_products_products"("strains_id");
CREATE INDEX IF NOT EXISTS "_m2m_strains_products_products_products_id_idx" ON "public"."_m2m_strains_products_products"("products_id");
ALTER TABLE "public"."_m2m_strains_products_products"
  ADD CONSTRAINT "_m2m_strains_products_products_strains_id_fk" FOREIGN KEY ("strains_id") REFERENCES "public"."strains"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_strains_products_products"
  ADD CONSTRAINT "_m2m_strains_products_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_recipes_lots_lots" (
  "recipes_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_recipes_lots_lots_recipes_id_idx" ON "public"."_m2m_recipes_lots_lots"("recipes_id");
CREATE INDEX IF NOT EXISTS "_m2m_recipes_lots_lots_lots_id_idx" ON "public"."_m2m_recipes_lots_lots"("lots_id");
ALTER TABLE "public"."_m2m_recipes_lots_lots"
  ADD CONSTRAINT "_m2m_recipes_lots_lots_recipes_id_fk" FOREIGN KEY ("recipes_id") REFERENCES "public"."recipes"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_recipes_lots_lots"
  ADD CONSTRAINT "_m2m_recipes_lots_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_recipes_sterilization_runs_sterilization_runs" (
  "recipes_id" bigint NOT NULL,
  "sterilization_runs_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_recipes_sterilization_runs_sterilization_runs_recipes_id_idx" ON "public"."_m2m_recipes_sterilization_runs_sterilization_runs"("recipes_id");
CREATE INDEX IF NOT EXISTS "_m2m_recipes_sterilization_runs_sterilization_runs_sterilization_runs_id_idx" ON "public"."_m2m_recipes_sterilization_runs_sterilization_runs"("sterilization_runs_id");
ALTER TABLE "public"."_m2m_recipes_sterilization_runs_sterilization_runs"
  ADD CONSTRAINT "_m2m_recipes_sterilization_runs_sterilization_runs_recipes_id_fk" FOREIGN KEY ("recipes_id") REFERENCES "public"."recipes"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_recipes_sterilization_runs_sterilization_runs"
  ADD CONSTRAINT "_m2m_recipes_sterilization_runs_sterilization_runs_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_items_item_id" (
  "products_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_items_item_id_products_id_idx" ON "public"."_m2m_products_items_item_id"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_items_item_id_items_id_idx" ON "public"."_m2m_products_items_item_id"("items_id");
ALTER TABLE "public"."_m2m_products_items_item_id"
  ADD CONSTRAINT "_m2m_products_items_item_id_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_items_item_id"
  ADD CONSTRAINT "_m2m_products_items_item_id_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_items_package_item" (
  "products_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_items_package_item_products_id_idx" ON "public"."_m2m_products_items_package_item"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_items_package_item_items_id_idx" ON "public"."_m2m_products_items_package_item"("items_id");
ALTER TABLE "public"."_m2m_products_items_package_item"
  ADD CONSTRAINT "_m2m_products_items_package_item_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_items_package_item"
  ADD CONSTRAINT "_m2m_products_items_package_item_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_locations_storage_location" (
  "products_id" bigint NOT NULL,
  "locations_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_locations_storage_location_products_id_idx" ON "public"."_m2m_products_locations_storage_location"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_locations_storage_location_locations_id_idx" ON "public"."_m2m_products_locations_storage_location"("locations_id");
ALTER TABLE "public"."_m2m_products_locations_storage_location"
  ADD CONSTRAINT "_m2m_products_locations_storage_location_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_locations_storage_location"
  ADD CONSTRAINT "_m2m_products_locations_storage_location_locations_id_fk" FOREIGN KEY ("locations_id") REFERENCES "public"."locations"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_products_merge_tray_products" (
  "products_id" bigint NOT NULL,
  "products1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_products_merge_tray_products_products_id_idx" ON "public"."_m2m_products_products_merge_tray_products"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_products_merge_tray_products_products1_id_idx" ON "public"."_m2m_products_products_merge_tray_products"("products1_id");
ALTER TABLE "public"."_m2m_products_products_merge_tray_products"
  ADD CONSTRAINT "_m2m_products_products_merge_tray_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_products_merge_tray_products"
  ADD CONSTRAINT "_m2m_products_products_merge_tray_products_products1_id_fk" FOREIGN KEY ("products1_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_lots_origin_lots" (
  "products_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_lots_origin_lots_products_id_idx" ON "public"."_m2m_products_lots_origin_lots"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_lots_origin_lots_lots_id_idx" ON "public"."_m2m_products_lots_origin_lots"("lots_id");
ALTER TABLE "public"."_m2m_products_lots_origin_lots"
  ADD CONSTRAINT "_m2m_products_lots_origin_lots_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_lots_origin_lots"
  ADD CONSTRAINT "_m2m_products_lots_origin_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_strains_strain_id" (
  "products_id" bigint NOT NULL,
  "strains_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_strains_strain_id_products_id_idx" ON "public"."_m2m_products_strains_strain_id"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_strains_strain_id_strains_id_idx" ON "public"."_m2m_products_strains_strain_id"("strains_id");
ALTER TABLE "public"."_m2m_products_strains_strain_id"
  ADD CONSTRAINT "_m2m_products_strains_strain_id_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_strains_strain_id"
  ADD CONSTRAINT "_m2m_products_strains_strain_id_strains_id_fk" FOREIGN KEY ("strains_id") REFERENCES "public"."strains"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_print_queue_print_queue" (
  "products_id" bigint NOT NULL,
  "print_queue_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_print_queue_print_queue_products_id_idx" ON "public"."_m2m_products_print_queue_print_queue"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_print_queue_print_queue_print_queue_id_idx" ON "public"."_m2m_products_print_queue_print_queue"("print_queue_id");
ALTER TABLE "public"."_m2m_products_print_queue_print_queue"
  ADD CONSTRAINT "_m2m_products_print_queue_print_queue_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_print_queue_print_queue"
  ADD CONSTRAINT "_m2m_products_print_queue_print_queue_print_queue_id_fk" FOREIGN KEY ("print_queue_id") REFERENCES "public"."print_queue"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_ecommerce_ecommerce" (
  "products_id" bigint NOT NULL,
  "ecommerce_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_ecommerce_ecommerce_products_id_idx" ON "public"."_m2m_products_ecommerce_ecommerce"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_ecommerce_ecommerce_ecommerce_id_idx" ON "public"."_m2m_products_ecommerce_ecommerce"("ecommerce_id");
ALTER TABLE "public"."_m2m_products_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_products_ecommerce_ecommerce_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_products_ecommerce_ecommerce_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_ecommerce_orders_ecommerce_orders" (
  "products_id" bigint NOT NULL,
  "ecommerce_orders_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_ecommerce_orders_ecommerce_orders_products_id_idx" ON "public"."_m2m_products_ecommerce_orders_ecommerce_orders"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_ecommerce_orders_ecommerce_orders_ecommerce_orders_id_idx" ON "public"."_m2m_products_ecommerce_orders_ecommerce_orders"("ecommerce_orders_id");
ALTER TABLE "public"."_m2m_products_ecommerce_orders_ecommerce_orders"
  ADD CONSTRAINT "_m2m_products_ecommerce_orders_ecommerce_orders_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_ecommerce_orders_ecommerce_orders"
  ADD CONSTRAINT "_m2m_products_ecommerce_orders_ecommerce_orders_ecommerce_orders_id_fk" FOREIGN KEY ("ecommerce_orders_id") REFERENCES "public"."ecommerce_orders"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_products_events_events" (
  "products_id" bigint NOT NULL,
  "events_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_products_events_events_products_id_idx" ON "public"."_m2m_products_events_events"("products_id");
CREATE INDEX IF NOT EXISTS "_m2m_products_events_events_events_id_idx" ON "public"."_m2m_products_events_events"("events_id");
ALTER TABLE "public"."_m2m_products_events_events"
  ADD CONSTRAINT "_m2m_products_events_events_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_products_events_events"
  ADD CONSTRAINT "_m2m_products_events_events_events_id_fk" FOREIGN KEY ("events_id") REFERENCES "public"."events"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_items_item_id" (
  "lots_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_items_item_id_lots_id_idx" ON "public"."_m2m_lots_items_item_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_items_item_id_items_id_idx" ON "public"."_m2m_lots_items_item_id"("items_id");
ALTER TABLE "public"."_m2m_lots_items_item_id"
  ADD CONSTRAINT "_m2m_lots_items_item_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_items_item_id"
  ADD CONSTRAINT "_m2m_lots_items_item_id_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_recipes_recipe_id" (
  "lots_id" bigint NOT NULL,
  "recipes_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_recipes_recipe_id_lots_id_idx" ON "public"."_m2m_lots_recipes_recipe_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_recipes_recipe_id_recipes_id_idx" ON "public"."_m2m_lots_recipes_recipe_id"("recipes_id");
ALTER TABLE "public"."_m2m_lots_recipes_recipe_id"
  ADD CONSTRAINT "_m2m_lots_recipes_recipe_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_recipes_recipe_id"
  ADD CONSTRAINT "_m2m_lots_recipes_recipe_id_recipes_id_fk" FOREIGN KEY ("recipes_id") REFERENCES "public"."recipes"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_strains_strain_id" (
  "lots_id" bigint NOT NULL,
  "strains_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_strains_strain_id_lots_id_idx" ON "public"."_m2m_lots_strains_strain_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_strains_strain_id_strains_id_idx" ON "public"."_m2m_lots_strains_strain_id"("strains_id");
ALTER TABLE "public"."_m2m_lots_strains_strain_id"
  ADD CONSTRAINT "_m2m_lots_strains_strain_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_strains_strain_id"
  ADD CONSTRAINT "_m2m_lots_strains_strain_id_strains_id_fk" FOREIGN KEY ("strains_id") REFERENCES "public"."strains"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_sterilization_runs_steri_run_id" (
  "lots_id" bigint NOT NULL,
  "sterilization_runs_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_sterilization_runs_steri_run_id_lots_id_idx" ON "public"."_m2m_lots_sterilization_runs_steri_run_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_sterilization_runs_steri_run_id_sterilization_runs_id_idx" ON "public"."_m2m_lots_sterilization_runs_steri_run_id"("sterilization_runs_id");
ALTER TABLE "public"."_m2m_lots_sterilization_runs_steri_run_id"
  ADD CONSTRAINT "_m2m_lots_sterilization_runs_steri_run_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_sterilization_runs_steri_run_id"
  ADD CONSTRAINT "_m2m_lots_sterilization_runs_steri_run_id_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_locations_location_id" (
  "lots_id" bigint NOT NULL,
  "locations_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_locations_location_id_lots_id_idx" ON "public"."_m2m_lots_locations_location_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_locations_location_id_locations_id_idx" ON "public"."_m2m_lots_locations_location_id"("locations_id");
ALTER TABLE "public"."_m2m_lots_locations_location_id"
  ADD CONSTRAINT "_m2m_lots_locations_location_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_locations_location_id"
  ADD CONSTRAINT "_m2m_lots_locations_location_id_locations_id_fk" FOREIGN KEY ("locations_id") REFERENCES "public"."locations"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_events_events" (
  "lots_id" bigint NOT NULL,
  "events_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_events_events_lots_id_idx" ON "public"."_m2m_lots_events_events"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_events_events_events_id_idx" ON "public"."_m2m_lots_events_events"("events_id");
ALTER TABLE "public"."_m2m_lots_events_events"
  ADD CONSTRAINT "_m2m_lots_events_events_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_events_events"
  ADD CONSTRAINT "_m2m_lots_events_events_events_id_fk" FOREIGN KEY ("events_id") REFERENCES "public"."events"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_lots_target_lot_ids" (
  "lots_id" bigint NOT NULL,
  "lots1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_target_lot_ids_lots_id_idx" ON "public"."_m2m_lots_lots_target_lot_ids"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_target_lot_ids_lots1_id_idx" ON "public"."_m2m_lots_lots_target_lot_ids"("lots1_id");
ALTER TABLE "public"."_m2m_lots_lots_target_lot_ids"
  ADD CONSTRAINT "_m2m_lots_lots_target_lot_ids_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_lots_target_lot_ids"
  ADD CONSTRAINT "_m2m_lots_lots_target_lot_ids_lots1_id_fk" FOREIGN KEY ("lots1_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_lots_grain_inputs" (
  "lots_id" bigint NOT NULL,
  "lots1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_grain_inputs_lots_id_idx" ON "public"."_m2m_lots_lots_grain_inputs"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_grain_inputs_lots1_id_idx" ON "public"."_m2m_lots_lots_grain_inputs"("lots1_id");
ALTER TABLE "public"."_m2m_lots_lots_grain_inputs"
  ADD CONSTRAINT "_m2m_lots_lots_grain_inputs_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_lots_grain_inputs"
  ADD CONSTRAINT "_m2m_lots_lots_grain_inputs_lots1_id_fk" FOREIGN KEY ("lots1_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_lots_substrate_inputs" (
  "lots_id" bigint NOT NULL,
  "lots1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_substrate_inputs_lots_id_idx" ON "public"."_m2m_lots_lots_substrate_inputs"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_substrate_inputs_lots1_id_idx" ON "public"."_m2m_lots_lots_substrate_inputs"("lots1_id");
ALTER TABLE "public"."_m2m_lots_lots_substrate_inputs"
  ADD CONSTRAINT "_m2m_lots_lots_substrate_inputs_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_lots_substrate_inputs"
  ADD CONSTRAINT "_m2m_lots_lots_substrate_inputs_lots1_id_fk" FOREIGN KEY ("lots1_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_items_syringe_item" (
  "lots_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_items_syringe_item_lots_id_idx" ON "public"."_m2m_lots_items_syringe_item"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_items_syringe_item_items_id_idx" ON "public"."_m2m_lots_items_syringe_item"("items_id");
ALTER TABLE "public"."_m2m_lots_items_syringe_item"
  ADD CONSTRAINT "_m2m_lots_items_syringe_item_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_items_syringe_item"
  ADD CONSTRAINT "_m2m_lots_items_syringe_item_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_items_harvest_item" (
  "lots_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_items_harvest_item_lots_id_idx" ON "public"."_m2m_lots_items_harvest_item"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_items_harvest_item_items_id_idx" ON "public"."_m2m_lots_items_harvest_item"("items_id");
ALTER TABLE "public"."_m2m_lots_items_harvest_item"
  ADD CONSTRAINT "_m2m_lots_items_harvest_item_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_items_harvest_item"
  ADD CONSTRAINT "_m2m_lots_items_harvest_item_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_products_products" (
  "lots_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_products_products_lots_id_idx" ON "public"."_m2m_lots_products_products"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_products_products_products_id_idx" ON "public"."_m2m_lots_products_products"("products_id");
ALTER TABLE "public"."_m2m_lots_products_products"
  ADD CONSTRAINT "_m2m_lots_products_products_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_products_products"
  ADD CONSTRAINT "_m2m_lots_products_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_lots_casing_lot_id" (
  "lots_id" bigint NOT NULL,
  "lots1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_casing_lot_id_lots_id_idx" ON "public"."_m2m_lots_lots_casing_lot_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_casing_lot_id_lots1_id_idx" ON "public"."_m2m_lots_lots_casing_lot_id"("lots1_id");
ALTER TABLE "public"."_m2m_lots_lots_casing_lot_id"
  ADD CONSTRAINT "_m2m_lots_lots_casing_lot_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_lots_casing_lot_id"
  ADD CONSTRAINT "_m2m_lots_lots_casing_lot_id_lots1_id_fk" FOREIGN KEY ("lots1_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_print_queue_print_queue" (
  "lots_id" bigint NOT NULL,
  "print_queue_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_print_queue_print_queue_lots_id_idx" ON "public"."_m2m_lots_print_queue_print_queue"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_print_queue_print_queue_print_queue_id_idx" ON "public"."_m2m_lots_print_queue_print_queue"("print_queue_id");
ALTER TABLE "public"."_m2m_lots_print_queue_print_queue"
  ADD CONSTRAINT "_m2m_lots_print_queue_print_queue_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_print_queue_print_queue"
  ADD CONSTRAINT "_m2m_lots_print_queue_print_queue_print_queue_id_fk" FOREIGN KEY ("print_queue_id") REFERENCES "public"."print_queue"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_lots_source_lot_id" (
  "lots_id" bigint NOT NULL,
  "lots1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_source_lot_id_lots_id_idx" ON "public"."_m2m_lots_lots_source_lot_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_source_lot_id_lots1_id_idx" ON "public"."_m2m_lots_lots_source_lot_id"("lots1_id");
ALTER TABLE "public"."_m2m_lots_lots_source_lot_id"
  ADD CONSTRAINT "_m2m_lots_lots_source_lot_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_lots_source_lot_id"
  ADD CONSTRAINT "_m2m_lots_lots_source_lot_id_lots1_id_fk" FOREIGN KEY ("lots1_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_lots_parent_lot_id" (
  "lots_id" bigint NOT NULL,
  "lots1_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_parent_lot_id_lots_id_idx" ON "public"."_m2m_lots_lots_parent_lot_id"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_lots_parent_lot_id_lots1_id_idx" ON "public"."_m2m_lots_lots_parent_lot_id"("lots1_id");
ALTER TABLE "public"."_m2m_lots_lots_parent_lot_id"
  ADD CONSTRAINT "_m2m_lots_lots_parent_lot_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_lots_parent_lot_id"
  ADD CONSTRAINT "_m2m_lots_lots_parent_lot_id_lots1_id_fk" FOREIGN KEY ("lots1_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_lots_ecommerce_ecommerce" (
  "lots_id" bigint NOT NULL,
  "ecommerce_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_lots_ecommerce_ecommerce_lots_id_idx" ON "public"."_m2m_lots_ecommerce_ecommerce"("lots_id");
CREATE INDEX IF NOT EXISTS "_m2m_lots_ecommerce_ecommerce_ecommerce_id_idx" ON "public"."_m2m_lots_ecommerce_ecommerce"("ecommerce_id");
ALTER TABLE "public"."_m2m_lots_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_lots_ecommerce_ecommerce_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_lots_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_lots_ecommerce_ecommerce_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_lots_lots" (
  "items_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_lots_lots_items_id_idx" ON "public"."_m2m_items_lots_lots"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_lots_lots_lots_id_idx" ON "public"."_m2m_items_lots_lots"("lots_id");
ALTER TABLE "public"."_m2m_items_lots_lots"
  ADD CONSTRAINT "_m2m_items_lots_lots_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_lots_lots"
  ADD CONSTRAINT "_m2m_items_lots_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_sterilization_runs_sterilization_runs" (
  "items_id" bigint NOT NULL,
  "sterilization_runs_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_sterilization_runs_sterilization_runs_items_id_idx" ON "public"."_m2m_items_sterilization_runs_sterilization_runs"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_sterilization_runs_sterilization_runs_sterilization_runs_id_idx" ON "public"."_m2m_items_sterilization_runs_sterilization_runs"("sterilization_runs_id");
ALTER TABLE "public"."_m2m_items_sterilization_runs_sterilization_runs"
  ADD CONSTRAINT "_m2m_items_sterilization_runs_sterilization_runs_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_sterilization_runs_sterilization_runs"
  ADD CONSTRAINT "_m2m_items_sterilization_runs_sterilization_runs_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_lots_lots_2" (
  "items_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_lots_lots_2_items_id_idx" ON "public"."_m2m_items_lots_lots_2"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_lots_lots_2_lots_id_idx" ON "public"."_m2m_items_lots_lots_2"("lots_id");
ALTER TABLE "public"."_m2m_items_lots_lots_2"
  ADD CONSTRAINT "_m2m_items_lots_lots_2_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_lots_lots_2"
  ADD CONSTRAINT "_m2m_items_lots_lots_2_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_products_products" (
  "items_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_products_products_items_id_idx" ON "public"."_m2m_items_products_products"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_products_products_products_id_idx" ON "public"."_m2m_items_products_products"("products_id");
ALTER TABLE "public"."_m2m_items_products_products"
  ADD CONSTRAINT "_m2m_items_products_products_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_products_products"
  ADD CONSTRAINT "_m2m_items_products_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_lots_lots_4" (
  "items_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_lots_lots_4_items_id_idx" ON "public"."_m2m_items_lots_lots_4"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_lots_lots_4_lots_id_idx" ON "public"."_m2m_items_lots_lots_4"("lots_id");
ALTER TABLE "public"."_m2m_items_lots_lots_4"
  ADD CONSTRAINT "_m2m_items_lots_lots_4_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_lots_lots_4"
  ADD CONSTRAINT "_m2m_items_lots_lots_4_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_products_products_2" (
  "items_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_products_products_2_items_id_idx" ON "public"."_m2m_items_products_products_2"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_products_products_2_products_id_idx" ON "public"."_m2m_items_products_products_2"("products_id");
ALTER TABLE "public"."_m2m_items_products_products_2"
  ADD CONSTRAINT "_m2m_items_products_products_2_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_products_products_2"
  ADD CONSTRAINT "_m2m_items_products_products_2_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_items_ecommerce_ecommerce" (
  "items_id" bigint NOT NULL,
  "ecommerce_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_items_ecommerce_ecommerce_items_id_idx" ON "public"."_m2m_items_ecommerce_ecommerce"("items_id");
CREATE INDEX IF NOT EXISTS "_m2m_items_ecommerce_ecommerce_ecommerce_id_idx" ON "public"."_m2m_items_ecommerce_ecommerce"("ecommerce_id");
ALTER TABLE "public"."_m2m_items_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_items_ecommerce_ecommerce_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_items_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_items_ecommerce_ecommerce_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_events_lots_lot_id" (
  "events_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_events_lots_lot_id_events_id_idx" ON "public"."_m2m_events_lots_lot_id"("events_id");
CREATE INDEX IF NOT EXISTS "_m2m_events_lots_lot_id_lots_id_idx" ON "public"."_m2m_events_lots_lot_id"("lots_id");
ALTER TABLE "public"."_m2m_events_lots_lot_id"
  ADD CONSTRAINT "_m2m_events_lots_lot_id_events_id_fk" FOREIGN KEY ("events_id") REFERENCES "public"."events"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_events_lots_lot_id"
  ADD CONSTRAINT "_m2m_events_lots_lot_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_events_products_product_id" (
  "events_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_events_products_product_id_events_id_idx" ON "public"."_m2m_events_products_product_id"("events_id");
CREATE INDEX IF NOT EXISTS "_m2m_events_products_product_id_products_id_idx" ON "public"."_m2m_events_products_product_id"("products_id");
ALTER TABLE "public"."_m2m_events_products_product_id"
  ADD CONSTRAINT "_m2m_events_products_product_id_events_id_fk" FOREIGN KEY ("events_id") REFERENCES "public"."events"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_events_products_product_id"
  ADD CONSTRAINT "_m2m_events_products_product_id_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_locations_lots_lots" (
  "locations_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_locations_lots_lots_locations_id_idx" ON "public"."_m2m_locations_lots_lots"("locations_id");
CREATE INDEX IF NOT EXISTS "_m2m_locations_lots_lots_lots_id_idx" ON "public"."_m2m_locations_lots_lots"("lots_id");
ALTER TABLE "public"."_m2m_locations_lots_lots"
  ADD CONSTRAINT "_m2m_locations_lots_lots_locations_id_fk" FOREIGN KEY ("locations_id") REFERENCES "public"."locations"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_locations_lots_lots"
  ADD CONSTRAINT "_m2m_locations_lots_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_locations_products_products" (
  "locations_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_locations_products_products_locations_id_idx" ON "public"."_m2m_locations_products_products"("locations_id");
CREATE INDEX IF NOT EXISTS "_m2m_locations_products_products_products_id_idx" ON "public"."_m2m_locations_products_products"("products_id");
ALTER TABLE "public"."_m2m_locations_products_products"
  ADD CONSTRAINT "_m2m_locations_products_products_locations_id_fk" FOREIGN KEY ("locations_id") REFERENCES "public"."locations"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_locations_products_products"
  ADD CONSTRAINT "_m2m_locations_products_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_sterilization_runs_items_planned_item" (
  "sterilization_runs_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_items_planned_item_sterilization_runs_id_idx" ON "public"."_m2m_sterilization_runs_items_planned_item"("sterilization_runs_id");
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_items_planned_item_items_id_idx" ON "public"."_m2m_sterilization_runs_items_planned_item"("items_id");
ALTER TABLE "public"."_m2m_sterilization_runs_items_planned_item"
  ADD CONSTRAINT "_m2m_sterilization_runs_items_planned_item_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_sterilization_runs_items_planned_item"
  ADD CONSTRAINT "_m2m_sterilization_runs_items_planned_item_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_sterilization_runs_recipes_planned_recipe" (
  "sterilization_runs_id" bigint NOT NULL,
  "recipes_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_recipes_planned_recipe_sterilization_runs_id_idx" ON "public"."_m2m_sterilization_runs_recipes_planned_recipe"("sterilization_runs_id");
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_recipes_planned_recipe_recipes_id_idx" ON "public"."_m2m_sterilization_runs_recipes_planned_recipe"("recipes_id");
ALTER TABLE "public"."_m2m_sterilization_runs_recipes_planned_recipe"
  ADD CONSTRAINT "_m2m_sterilization_runs_recipes_planned_recipe_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_sterilization_runs_recipes_planned_recipe"
  ADD CONSTRAINT "_m2m_sterilization_runs_recipes_planned_recipe_recipes_id_fk" FOREIGN KEY ("recipes_id") REFERENCES "public"."recipes"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_sterilization_runs_lots_lots" (
  "sterilization_runs_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_lots_lots_sterilization_runs_id_idx" ON "public"."_m2m_sterilization_runs_lots_lots"("sterilization_runs_id");
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_lots_lots_lots_id_idx" ON "public"."_m2m_sterilization_runs_lots_lots"("lots_id");
ALTER TABLE "public"."_m2m_sterilization_runs_lots_lots"
  ADD CONSTRAINT "_m2m_sterilization_runs_lots_lots_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_sterilization_runs_lots_lots"
  ADD CONSTRAINT "_m2m_sterilization_runs_lots_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_sterilization_runs_print_queue_print_queue" (
  "sterilization_runs_id" bigint NOT NULL,
  "print_queue_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_print_queue_print_queue_sterilization_runs_id_idx" ON "public"."_m2m_sterilization_runs_print_queue_print_queue"("sterilization_runs_id");
CREATE INDEX IF NOT EXISTS "_m2m_sterilization_runs_print_queue_print_queue_print_queue_id_idx" ON "public"."_m2m_sterilization_runs_print_queue_print_queue"("print_queue_id");
ALTER TABLE "public"."_m2m_sterilization_runs_print_queue_print_queue"
  ADD CONSTRAINT "_m2m_sterilization_runs_print_queue_print_queue_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_sterilization_runs_print_queue_print_queue"
  ADD CONSTRAINT "_m2m_sterilization_runs_print_queue_print_queue_print_queue_id_fk" FOREIGN KEY ("print_queue_id") REFERENCES "public"."print_queue"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_print_queue_lots_lot_id" (
  "print_queue_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_print_queue_lots_lot_id_print_queue_id_idx" ON "public"."_m2m_print_queue_lots_lot_id"("print_queue_id");
CREATE INDEX IF NOT EXISTS "_m2m_print_queue_lots_lot_id_lots_id_idx" ON "public"."_m2m_print_queue_lots_lot_id"("lots_id");
ALTER TABLE "public"."_m2m_print_queue_lots_lot_id"
  ADD CONSTRAINT "_m2m_print_queue_lots_lot_id_print_queue_id_fk" FOREIGN KEY ("print_queue_id") REFERENCES "public"."print_queue"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_print_queue_lots_lot_id"
  ADD CONSTRAINT "_m2m_print_queue_lots_lot_id_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_print_queue_products_product_id" (
  "print_queue_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_print_queue_products_product_id_print_queue_id_idx" ON "public"."_m2m_print_queue_products_product_id"("print_queue_id");
CREATE INDEX IF NOT EXISTS "_m2m_print_queue_products_product_id_products_id_idx" ON "public"."_m2m_print_queue_products_product_id"("products_id");
ALTER TABLE "public"."_m2m_print_queue_products_product_id"
  ADD CONSTRAINT "_m2m_print_queue_products_product_id_print_queue_id_fk" FOREIGN KEY ("print_queue_id") REFERENCES "public"."print_queue"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_print_queue_products_product_id"
  ADD CONSTRAINT "_m2m_print_queue_products_product_id_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_print_queue_sterilization_runs_run_id" (
  "print_queue_id" bigint NOT NULL,
  "sterilization_runs_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_print_queue_sterilization_runs_run_id_print_queue_id_idx" ON "public"."_m2m_print_queue_sterilization_runs_run_id"("print_queue_id");
CREATE INDEX IF NOT EXISTS "_m2m_print_queue_sterilization_runs_run_id_sterilization_runs_id_idx" ON "public"."_m2m_print_queue_sterilization_runs_run_id"("sterilization_runs_id");
ALTER TABLE "public"."_m2m_print_queue_sterilization_runs_run_id"
  ADD CONSTRAINT "_m2m_print_queue_sterilization_runs_run_id_print_queue_id_fk" FOREIGN KEY ("print_queue_id") REFERENCES "public"."print_queue"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_print_queue_sterilization_runs_run_id"
  ADD CONSTRAINT "_m2m_print_queue_sterilization_runs_run_id_sterilization_runs_id_fk" FOREIGN KEY ("sterilization_runs_id") REFERENCES "public"."sterilization_runs"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_items_item_id" (
  "ecommerce_id" bigint NOT NULL,
  "items_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_items_item_id_ecommerce_id_idx" ON "public"."_m2m_ecommerce_items_item_id"("ecommerce_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_items_item_id_items_id_idx" ON "public"."_m2m_ecommerce_items_item_id"("items_id");
ALTER TABLE "public"."_m2m_ecommerce_items_item_id"
  ADD CONSTRAINT "_m2m_ecommerce_items_item_id_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_items_item_id"
  ADD CONSTRAINT "_m2m_ecommerce_items_item_id_items_id_fk" FOREIGN KEY ("items_id") REFERENCES "public"."items"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_strains_strain_id" (
  "ecommerce_id" bigint NOT NULL,
  "strains_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_strains_strain_id_ecommerce_id_idx" ON "public"."_m2m_ecommerce_strains_strain_id"("ecommerce_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_strains_strain_id_strains_id_idx" ON "public"."_m2m_ecommerce_strains_strain_id"("strains_id");
ALTER TABLE "public"."_m2m_ecommerce_strains_strain_id"
  ADD CONSTRAINT "_m2m_ecommerce_strains_strain_id_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_strains_strain_id"
  ADD CONSTRAINT "_m2m_ecommerce_strains_strain_id_strains_id_fk" FOREIGN KEY ("strains_id") REFERENCES "public"."strains"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_products_products" (
  "ecommerce_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_products_products_ecommerce_id_idx" ON "public"."_m2m_ecommerce_products_products"("ecommerce_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_products_products_products_id_idx" ON "public"."_m2m_ecommerce_products_products"("products_id");
ALTER TABLE "public"."_m2m_ecommerce_products_products"
  ADD CONSTRAINT "_m2m_ecommerce_products_products_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_products_products"
  ADD CONSTRAINT "_m2m_ecommerce_products_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_lots_lots" (
  "ecommerce_id" bigint NOT NULL,
  "lots_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_lots_lots_ecommerce_id_idx" ON "public"."_m2m_ecommerce_lots_lots"("ecommerce_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_lots_lots_lots_id_idx" ON "public"."_m2m_ecommerce_lots_lots"("lots_id");
ALTER TABLE "public"."_m2m_ecommerce_lots_lots"
  ADD CONSTRAINT "_m2m_ecommerce_lots_lots_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_lots_lots"
  ADD CONSTRAINT "_m2m_ecommerce_lots_lots_lots_id_fk" FOREIGN KEY ("lots_id") REFERENCES "public"."lots"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_ecommerce_orders_ecommerce_orders" (
  "ecommerce_id" bigint NOT NULL,
  "ecommerce_orders_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_ecommerce_orders_ecommerce_orders_ecommerce_id_idx" ON "public"."_m2m_ecommerce_ecommerce_orders_ecommerce_orders"("ecommerce_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_ecommerce_orders_ecommerce_orders_ecommerce_orders_id_idx" ON "public"."_m2m_ecommerce_ecommerce_orders_ecommerce_orders"("ecommerce_orders_id");
ALTER TABLE "public"."_m2m_ecommerce_ecommerce_orders_ecommerce_orders"
  ADD CONSTRAINT "_m2m_ecommerce_ecommerce_orders_ecommerce_orders_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_ecommerce_orders_ecommerce_orders"
  ADD CONSTRAINT "_m2m_ecommerce_ecommerce_orders_ecommerce_orders_ecommerce_orders_id_fk" FOREIGN KEY ("ecommerce_orders_id") REFERENCES "public"."ecommerce_orders"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_orders_products_products" (
  "ecommerce_orders_id" bigint NOT NULL,
  "products_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_orders_products_products_ecommerce_orders_id_idx" ON "public"."_m2m_ecommerce_orders_products_products"("ecommerce_orders_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_orders_products_products_products_id_idx" ON "public"."_m2m_ecommerce_orders_products_products"("products_id");
ALTER TABLE "public"."_m2m_ecommerce_orders_products_products"
  ADD CONSTRAINT "_m2m_ecommerce_orders_products_products_ecommerce_orders_id_fk" FOREIGN KEY ("ecommerce_orders_id") REFERENCES "public"."ecommerce_orders"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_orders_products_products"
  ADD CONSTRAINT "_m2m_ecommerce_orders_products_products_products_id_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("nocopk") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "public"."_m2m_ecommerce_orders_ecommerce_ecommerce" (
  "ecommerce_orders_id" bigint NOT NULL,
  "ecommerce_id" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_orders_ecommerce_ecommerce_ecommerce_orders_id_idx" ON "public"."_m2m_ecommerce_orders_ecommerce_ecommerce"("ecommerce_orders_id");
CREATE INDEX IF NOT EXISTS "_m2m_ecommerce_orders_ecommerce_ecommerce_ecommerce_id_idx" ON "public"."_m2m_ecommerce_orders_ecommerce_ecommerce"("ecommerce_id");
ALTER TABLE "public"."_m2m_ecommerce_orders_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_ecommerce_orders_ecommerce_ecommerce_ecommerce_orders_id_fk" FOREIGN KEY ("ecommerce_orders_id") REFERENCES "public"."ecommerce_orders"("nocopk") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."_m2m_ecommerce_orders_ecommerce_ecommerce"
  ADD CONSTRAINT "_m2m_ecommerce_orders_ecommerce_ecommerce_ecommerce_id_fk" FOREIGN KEY ("ecommerce_id") REFERENCES "public"."ecommerce"("nocopk") DEFERRABLE INITIALLY DEFERRED;

COMMIT;
