-- Generated by airtable_export_to_postgres_sql_v3.js
-- 2026-01-29T21:53:12.927Z
BEGIN;
DROP VIEW IF EXISTS "public"."v_strains" CASCADE;
DROP VIEW IF EXISTS "public"."v_recipes" CASCADE;
DROP VIEW IF EXISTS "public"."v_products" CASCADE;
DROP VIEW IF EXISTS "public"."v_lots" CASCADE;
DROP VIEW IF EXISTS "public"."v_items" CASCADE;
DROP VIEW IF EXISTS "public"."v_events" CASCADE;
DROP VIEW IF EXISTS "public"."v_locations" CASCADE;
DROP VIEW IF EXISTS "public"."v_sterilization_runs" CASCADE;
DROP VIEW IF EXISTS "public"."v_print_queue" CASCADE;
DROP VIEW IF EXISTS "public"."v_ecommerce" CASCADE;
DROP VIEW IF EXISTS "public"."v_ecommerce_orders" CASCADE;

CREATE VIEW "public"."v_strains" AS
SELECT
  t.*,
  'public.strains'::text AS __table,
  COALESCE(t."strain_id"::text, t."nocopk"::text) AS __primary,
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_strains_lots_lots" j WHERE j."strains_id" = t."nocopk") AS "strains__lots__lots__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_id" ORDER BY j."ecommerce_id"), '{}'::bigint[]) FROM "public"."_m2m_strains_ecommerce_ecommerce" j WHERE j."strains_id" = t."nocopk") AS "strains__ecommerce__ecommerce__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_strains_products_products" j WHERE j."strains_id" = t."nocopk") AS "strains__products__products__ids"
FROM "public"."strains" t;

CREATE VIEW "public"."v_recipes" AS
SELECT
  t.*,
  'public.recipes'::text AS __table,
  COALESCE(t."recipe_id"::text, t."nocopk"::text) AS __primary,
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_recipes_lots_lots" j WHERE j."recipes_id" = t."nocopk") AS "recipes__lots__lots__ids",
  (SELECT COALESCE(array_agg(j."sterilization_runs_id" ORDER BY j."sterilization_runs_id"), '{}'::bigint[]) FROM "public"."_m2m_recipes_sterilization_runs_sterilization_runs" j WHERE j."recipes_id" = t."nocopk") AS "recipes__sterilization_runs__sterilization_runs__ids"
FROM "public"."recipes" t;

CREATE VIEW "public"."v_products" AS
SELECT
  t.*,
  'public.products'::text AS __table,
  t."nocopk"::text AS __primary,
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_products_items_item_id" j WHERE j."products_id" = t."nocopk") AS "products__items__item_id__ids",
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_products_items_package_item" j WHERE j."products_id" = t."nocopk") AS "products__items__package_item__ids",
  (SELECT COALESCE(array_agg(j."locations_id" ORDER BY j."locations_id"), '{}'::bigint[]) FROM "public"."_m2m_products_locations_storage_location" j WHERE j."products_id" = t."nocopk") AS "products__locations__storage_location__ids",
  (SELECT COALESCE(array_agg(j."products1_id" ORDER BY j."products1_id"), '{}'::bigint[]) FROM "public"."_m2m_products_products_merge_tray_products" j WHERE j."products_id" = t."nocopk") AS "products__products__merge_tray_products__ids",
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_products_lots_origin_lots" j WHERE j."products_id" = t."nocopk") AS "products__lots__origin_lots__ids",
  (SELECT COALESCE(array_agg(j."strains_id" ORDER BY j."strains_id"), '{}'::bigint[]) FROM "public"."_m2m_products_strains_strain_id" j WHERE j."products_id" = t."nocopk") AS "products__strains__strain_id__ids",
  (SELECT COALESCE(array_agg(j."print_queue_id" ORDER BY j."print_queue_id"), '{}'::bigint[]) FROM "public"."_m2m_products_print_queue_print_queue" j WHERE j."products_id" = t."nocopk") AS "products__print_queue__print_queue__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_id" ORDER BY j."ecommerce_id"), '{}'::bigint[]) FROM "public"."_m2m_products_ecommerce_ecommerce" j WHERE j."products_id" = t."nocopk") AS "products__ecommerce__ecommerce__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_orders_id" ORDER BY j."ecommerce_orders_id"), '{}'::bigint[]) FROM "public"."_m2m_products_ecommerce_orders_ecommerce_orders" j WHERE j."products_id" = t."nocopk") AS "products__ecommerce_orders__ecommerce_orders__ids",
  (SELECT COALESCE(array_agg(j."events_id" ORDER BY j."events_id"), '{}'::bigint[]) FROM "public"."_m2m_products_events_events" j WHERE j."products_id" = t."nocopk") AS "products__events__events__ids"
FROM "public"."products" t;

CREATE VIEW "public"."v_lots" AS
SELECT
  t.*,
  'public.lots'::text AS __table,
  t."nocopk"::text AS __primary,
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_items_item_id" j WHERE j."lots_id" = t."nocopk") AS "lots__items__item_id__ids",
  (SELECT COALESCE(array_agg(j."recipes_id" ORDER BY j."recipes_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_recipes_recipe_id" j WHERE j."lots_id" = t."nocopk") AS "lots__recipes__recipe_id__ids",
  (SELECT COALESCE(array_agg(j."strains_id" ORDER BY j."strains_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_strains_strain_id" j WHERE j."lots_id" = t."nocopk") AS "lots__strains__strain_id__ids",
  (SELECT COALESCE(array_agg(j."sterilization_runs_id" ORDER BY j."sterilization_runs_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_sterilization_runs_steri_run_id" j WHERE j."lots_id" = t."nocopk") AS "lots__sterilization_runs__steri_run_id__ids",
  (SELECT COALESCE(array_agg(j."locations_id" ORDER BY j."locations_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_locations_location_id" j WHERE j."lots_id" = t."nocopk") AS "lots__locations__location_id__ids",
  (SELECT COALESCE(array_agg(j."events_id" ORDER BY j."events_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_events_events" j WHERE j."lots_id" = t."nocopk") AS "lots__events__events__ids",
  (SELECT COALESCE(array_agg(j."lots1_id" ORDER BY j."lots1_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_lots_target_lot_ids" j WHERE j."lots_id" = t."nocopk") AS "lots__lots__target_lot_ids__ids",
  (SELECT COALESCE(array_agg(j."lots1_id" ORDER BY j."lots1_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_lots_grain_inputs" j WHERE j."lots_id" = t."nocopk") AS "lots__lots__grain_inputs__ids",
  (SELECT COALESCE(array_agg(j."lots1_id" ORDER BY j."lots1_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_lots_substrate_inputs" j WHERE j."lots_id" = t."nocopk") AS "lots__lots__substrate_inputs__ids",
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_items_syringe_item" j WHERE j."lots_id" = t."nocopk") AS "lots__items__syringe_item__ids",
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_items_harvest_item" j WHERE j."lots_id" = t."nocopk") AS "lots__items__harvest_item__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_products_products" j WHERE j."lots_id" = t."nocopk") AS "lots__products__products__ids",
  (SELECT COALESCE(array_agg(j."lots1_id" ORDER BY j."lots1_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_lots_casing_lot_id" j WHERE j."lots_id" = t."nocopk") AS "lots__lots__casing_lot_id__ids",
  (SELECT COALESCE(array_agg(j."print_queue_id" ORDER BY j."print_queue_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_print_queue_print_queue" j WHERE j."lots_id" = t."nocopk") AS "lots__print_queue__print_queue__ids",
  (SELECT COALESCE(array_agg(j."lots1_id" ORDER BY j."lots1_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_lots_source_lot_id" j WHERE j."lots_id" = t."nocopk") AS "lots__lots__source_lot_id__ids",
  (SELECT COALESCE(array_agg(j."lots1_id" ORDER BY j."lots1_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_lots_parent_lot_id" j WHERE j."lots_id" = t."nocopk") AS "lots__lots__parent_lot_id__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_id" ORDER BY j."ecommerce_id"), '{}'::bigint[]) FROM "public"."_m2m_lots_ecommerce_ecommerce" j WHERE j."lots_id" = t."nocopk") AS "lots__ecommerce__ecommerce__ids"
FROM "public"."lots" t;

CREATE VIEW "public"."v_items" AS
SELECT
  t.*,
  'public.items'::text AS __table,
  COALESCE(t."item_id"::text, t."nocopk"::text) AS __primary,
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_items_lots_lots" j WHERE j."items_id" = t."nocopk") AS "items__lots__lots__ids",
  (SELECT COALESCE(array_agg(j."sterilization_runs_id" ORDER BY j."sterilization_runs_id"), '{}'::bigint[]) FROM "public"."_m2m_items_sterilization_runs_sterilization_runs" j WHERE j."items_id" = t."nocopk") AS "items__sterilization_runs__sterilization_runs__ids",
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_items_lots_lots_2" j WHERE j."items_id" = t."nocopk") AS "items__lots__lots_2__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_items_products_products" j WHERE j."items_id" = t."nocopk") AS "items__products__products__ids",
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_items_lots_lots_4" j WHERE j."items_id" = t."nocopk") AS "items__lots__lots_4__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_items_products_products_2" j WHERE j."items_id" = t."nocopk") AS "items__products__products_2__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_id" ORDER BY j."ecommerce_id"), '{}'::bigint[]) FROM "public"."_m2m_items_ecommerce_ecommerce" j WHERE j."items_id" = t."nocopk") AS "items__ecommerce__ecommerce__ids"
FROM "public"."items" t;

CREATE VIEW "public"."v_events" AS
SELECT
  t.*,
  'public.events'::text AS __table,
  t."nocopk"::text AS __primary,
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_events_lots_lot_id" j WHERE j."events_id" = t."nocopk") AS "events__lots__lot_id__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_events_products_product_id" j WHERE j."events_id" = t."nocopk") AS "events__products__product_id__ids"
FROM "public"."events" t;

CREATE VIEW "public"."v_locations" AS
SELECT
  t.*,
  'public.locations'::text AS __table,
  COALESCE(t."name"::text, t."nocopk"::text) AS __primary,
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_locations_lots_lots" j WHERE j."locations_id" = t."nocopk") AS "locations__lots__lots__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_locations_products_products" j WHERE j."locations_id" = t."nocopk") AS "locations__products__products__ids"
FROM "public"."locations" t;

CREATE VIEW "public"."v_sterilization_runs" AS
SELECT
  t.*,
  'public.sterilization_runs'::text AS __table,
  t."nocopk"::text AS __primary,
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_sterilization_runs_items_planned_item" j WHERE j."sterilization_runs_id" = t."nocopk") AS "sterilization_runs__items__planned_item__ids",
  (SELECT COALESCE(array_agg(j."recipes_id" ORDER BY j."recipes_id"), '{}'::bigint[]) FROM "public"."_m2m_sterilization_runs_recipes_planned_recipe" j WHERE j."sterilization_runs_id" = t."nocopk") AS "sterilization_runs__recipes__planned_recipe__ids",
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_sterilization_runs_lots_lots" j WHERE j."sterilization_runs_id" = t."nocopk") AS "sterilization_runs__lots__lots__ids",
  (SELECT COALESCE(array_agg(j."print_queue_id" ORDER BY j."print_queue_id"), '{}'::bigint[]) FROM "public"."_m2m_sterilization_runs_print_queue_print_queue" j WHERE j."sterilization_runs_id" = t."nocopk") AS "sterilization_runs__print_queue__print_queue__ids"
FROM "public"."sterilization_runs" t;

CREATE VIEW "public"."v_print_queue" AS
SELECT
  t.*,
  'public.print_queue'::text AS __table,
  t."nocopk"::text AS __primary,
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_print_queue_lots_lot_id" j WHERE j."print_queue_id" = t."nocopk") AS "print_queue__lots__lot_id__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_print_queue_products_product_id" j WHERE j."print_queue_id" = t."nocopk") AS "print_queue__products__product_id__ids",
  (SELECT COALESCE(array_agg(j."sterilization_runs_id" ORDER BY j."sterilization_runs_id"), '{}'::bigint[]) FROM "public"."_m2m_print_queue_sterilization_runs_run_id" j WHERE j."print_queue_id" = t."nocopk") AS "print_queue__sterilization_runs__run_id__ids"
FROM "public"."print_queue" t;

CREATE VIEW "public"."v_ecommerce" AS
SELECT
  t.*,
  'public.ecommerce'::text AS __table,
  COALESCE(t."name"::text, t."nocopk"::text) AS __primary,
  (SELECT COALESCE(array_agg(j."items_id" ORDER BY j."items_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_items_item_id" j WHERE j."ecommerce_id" = t."nocopk") AS "ecommerce__items__item_id__ids",
  (SELECT COALESCE(array_agg(j."strains_id" ORDER BY j."strains_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_strains_strain_id" j WHERE j."ecommerce_id" = t."nocopk") AS "ecommerce__strains__strain_id__ids",
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_products_products" j WHERE j."ecommerce_id" = t."nocopk") AS "ecommerce__products__products__ids",
  (SELECT COALESCE(array_agg(j."lots_id" ORDER BY j."lots_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_lots_lots" j WHERE j."ecommerce_id" = t."nocopk") AS "ecommerce__lots__lots__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_orders_id" ORDER BY j."ecommerce_orders_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_ecommerce_orders_ecommerce_orders" j WHERE j."ecommerce_id" = t."nocopk") AS "ecommerce__ecommerce_orders__ecommerce_orders__ids"
FROM "public"."ecommerce" t;

CREATE VIEW "public"."v_ecommerce_orders" AS
SELECT
  t.*,
  'public.ecommerce_orders'::text AS __table,
  COALESCE(t."name"::text, t."nocopk"::text) AS __primary,
  (SELECT COALESCE(array_agg(j."products_id" ORDER BY j."products_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_orders_products_products" j WHERE j."ecommerce_orders_id" = t."nocopk") AS "ecommerce_orders__products__products__ids",
  (SELECT COALESCE(array_agg(j."ecommerce_id" ORDER BY j."ecommerce_id"), '{}'::bigint[]) FROM "public"."_m2m_ecommerce_orders_ecommerce_ecommerce" j WHERE j."ecommerce_orders_id" = t."nocopk") AS "ecommerce_orders__ecommerce__ecommerce__ids"
FROM "public"."ecommerce_orders" t;

COMMIT;
