-- Generated by airtable_export_to_postgres_sql_v2_latest.js
-- 2026-01-25T19:18:46.703Z
BEGIN;
DROP VIEW IF EXISTS "public"."vc_strains" CASCADE;
DROP VIEW IF EXISTS "public"."vc_recipes" CASCADE;
DROP VIEW IF EXISTS "public"."vc_products" CASCADE;
DROP VIEW IF EXISTS "public"."vc_lots" CASCADE;
DROP VIEW IF EXISTS "public"."vc_items" CASCADE;
DROP VIEW IF EXISTS "public"."vc_events" CASCADE;
DROP VIEW IF EXISTS "public"."vc_locations" CASCADE;
DROP VIEW IF EXISTS "public"."vc_sterilization_runs" CASCADE;
DROP VIEW IF EXISTS "public"."vc_print_queue" CASCADE;
DROP VIEW IF EXISTS "public"."vc_ecommerce" CASCADE;
DROP VIEW IF EXISTS "public"."vc_ecommerce_orders" CASCADE;

CREATE VIEW "public"."vc_strains" AS SELECT * FROM "public"."v_strains";

CREATE VIEW "public"."vc_recipes" AS SELECT * FROM "public"."v_recipes";

CREATE VIEW "public"."vc_products" AS
SELECT base.*,
  (SELECT COALESCE(array_agg(btbl."name"::text ORDER BY btbl."name"::text) FILTER (WHERE btbl."name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_items_item_id" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."products_id" = base.nocopk) AS "name",
  (SELECT COALESCE(array_agg(btbl."category"::text ORDER BY btbl."category"::text) FILTER (WHERE btbl."category" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_items_item_id" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."products_id" = base.nocopk) AS "item_category",
  (SELECT COALESCE(array_agg(btbl."name"::text ORDER BY btbl."name"::text) FILTER (WHERE btbl."name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_items_package_item" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."products_id" = base.nocopk) AS "name_from_package_item",
  (SELECT COALESCE(array_agg(btbl."category"::text ORDER BY btbl."category"::text) FILTER (WHERE btbl."category" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_items_package_item" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."products_id" = base.nocopk) AS "package_item_category",
  '{}'::text[] AS "unit_lbs",
  (SELECT COALESCE(array_agg(btbl."unit_size"::text ORDER BY btbl."unit_size"::text) FILTER (WHERE btbl."unit_size" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_lots_origin_lots" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots_id" WHERE j."products_id" = base.nocopk) AS "unit_size",
  '{}'::text[] AS "label_inoc_prod",
  '{}'::text[] AS "label_spawned_prod",
  '{}'::text[] AS "label_proc_prod",
  '{}'::text[] AS "process_type",
  (SELECT COALESCE(array_agg(btbl."species_strain"::text ORDER BY btbl."species_strain"::text) FILTER (WHERE btbl."species_strain" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_strains_strain_id" j JOIN "public"."strains" btbl ON btbl.nocopk = j."strains_id" WHERE j."products_id" = base.nocopk) AS "species_strain",
  (SELECT COALESCE(array_agg(btbl."regulated"::text ORDER BY btbl."regulated"::text) FILTER (WHERE btbl."regulated" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_products_strains_strain_id" j JOIN "public"."strains" btbl ON btbl.nocopk = j."strains_id" WHERE j."products_id" = base.nocopk) AS "origin_strain_regulated"
FROM "public"."v_products" base;

-- TODO(rollup): lots.inoculated_at (from grain_inputs) (aggregation formula not exported); emitted as array_agg
-- TODO(rollup): lots.spawned_date (aggregation formula not exported); emitted as array_agg
-- TODO(rollup): lots.last_inoculation_date (aggregation formula not exported); emitted as array_agg
-- TODO(rollup): lots.first_event_date (aggregation formula not exported); emitted as array_agg
-- TODO(rollup): lots.last_event_date (aggregation formula not exported); emitted as array_agg
CREATE VIEW "public"."vc_lots" AS
SELECT base.*,
  (SELECT COALESCE(array_agg(btbl."name"::text ORDER BY btbl."name"::text) FILTER (WHERE btbl."name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_items_item_id" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."lots_id" = base.nocopk) AS "item_name",
  (SELECT COALESCE(array_agg(btbl."name"::text ORDER BY btbl."name"::text) FILTER (WHERE btbl."name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_recipes_recipe_id" j JOIN "public"."recipes" btbl ON btbl.nocopk = j."recipes_id" WHERE j."lots_id" = base.nocopk) AS "recipe_name",
  (SELECT COALESCE(array_agg(btbl."regulated"::text ORDER BY btbl."regulated"::text) FILTER (WHERE btbl."regulated" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_strains_strain_id" j JOIN "public"."strains" btbl ON btbl.nocopk = j."strains_id" WHERE j."lots_id" = base.nocopk) AS "regulated_from_strain_id",
  (SELECT COALESCE(array_agg(btbl."species_strain"::text ORDER BY btbl."species_strain"::text) FILTER (WHERE btbl."species_strain" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_strains_strain_id" j JOIN "public"."strains" btbl ON btbl.nocopk = j."strains_id" WHERE j."lots_id" = base.nocopk) AS "strain_species_strain",
  (SELECT COALESCE(array_agg(btbl."process_type"::text ORDER BY btbl."process_type"::text) FILTER (WHERE btbl."process_type" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_sterilization_runs_steri_run_id" j JOIN "public"."sterilization_runs" btbl ON btbl.nocopk = j."sterilization_runs_id" WHERE j."lots_id" = base.nocopk) AS "process_type_from_steri_run_id",
  (SELECT COALESCE(array_agg(btbl."category"::text ORDER BY btbl."category"::text) FILTER (WHERE btbl."category" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_items_item_id" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."lots_id" = base.nocopk) AS "item_category",
  '{}'::text[] AS "strain_species_strain_from_lc_lot_id",
  (SELECT COALESCE(array_agg(btbl."vendor_name"::text ORDER BY btbl."vendor_name"::text) FILTER (WHERE btbl."vendor_name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_lots_target_lot_ids" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots1_id" WHERE j."lots_id" = base.nocopk) AS "vendor_name_from_lc_lot_id",
  (SELECT COALESCE(array_agg(btbl."item_name_mat"::text ORDER BY btbl."item_name_mat"::text) FILTER (WHERE btbl."item_name_mat" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_lots_grain_inputs" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots1_id" WHERE j."lots_id" = base.nocopk) AS "item_name_mat_from_grain_inputs",
  (SELECT COALESCE(array_agg(btbl."inoculated_at"::text ORDER BY btbl."inoculated_at"::text) FILTER (WHERE btbl."inoculated_at" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_lots_grain_inputs" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots1_id" WHERE j."lots_id" = base.nocopk) AS "inoculated_at_from_grain_inputs",
  (SELECT COALESCE(array_agg(btbl."process_type_mat"::text ORDER BY btbl."process_type_mat"::text) FILTER (WHERE btbl."process_type_mat" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_lots_substrate_inputs" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots1_id" WHERE j."lots_id" = base.nocopk) AS "process_type_mat_from_substrate_inputs",
  (SELECT COALESCE(array_agg(btbl."item_name_mat"::text ORDER BY btbl."item_name_mat"::text) FILTER (WHERE btbl."item_name_mat" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_lots_substrate_inputs" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots1_id" WHERE j."lots_id" = base.nocopk) AS "item_name_mat_from_substrate_inputs",
  (SELECT COALESCE(array_agg(btbl."category"::text ORDER BY btbl."category"::text) FILTER (WHERE btbl."category" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_items_harvest_item" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."lots_id" = base.nocopk) AS "harvest_item_category",
  '{}'::text[] AS "name_from_products",
  '{}'::text[] AS "category_from_item_id_from_products",
  (SELECT COALESCE(array_agg(btbl."timestamp"::text ORDER BY btbl."timestamp"::text) FILTER (WHERE btbl."timestamp" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_events_events" j JOIN "public"."events" btbl ON btbl.nocopk = j."events_id" WHERE j."lots_id" = base.nocopk) AS "spawned_date",
  (SELECT COALESCE(array_agg(btbl."timestamp"::text ORDER BY btbl."timestamp"::text) FILTER (WHERE btbl."timestamp" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_events_events" j JOIN "public"."events" btbl ON btbl.nocopk = j."events_id" WHERE j."lots_id" = base.nocopk) AS "last_inoculation_date",
  (SELECT COALESCE(array_agg(btbl."timestamp"::text ORDER BY btbl."timestamp"::text) FILTER (WHERE btbl."timestamp" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_events_events" j JOIN "public"."events" btbl ON btbl.nocopk = j."events_id" WHERE j."lots_id" = base.nocopk) AS "first_event_date",
  (SELECT COALESCE(array_agg(btbl."timestamp"::text ORDER BY btbl."timestamp"::text) FILTER (WHERE btbl."timestamp" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_lots_events_events" j JOIN "public"."events" btbl ON btbl.nocopk = j."events_id" WHERE j."lots_id" = base.nocopk) AS "last_event_date"
FROM "public"."v_lots" base;

CREATE VIEW "public"."vc_items" AS SELECT * FROM "public"."v_items";

CREATE VIEW "public"."vc_events" AS
SELECT base.*,
  (SELECT COALESCE(array_agg(btbl."status"::text ORDER BY btbl."status"::text) FILTER (WHERE btbl."status" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_events_lots_lot_id" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots_id" WHERE j."events_id" = base.nocopk) AS "status_from_lot_id",
  '{}'::text[] AS "storage_location_from_product_id",
  '{}'::text[] AS "grain_inputs_from_lot_id",
  '{}'::text[] AS "substrate_inputs_from_lot_id",
  '{}'::text[] AS "vendor_name_from_lc_lot_id_from_lot_id",
  '{}'::text[] AS "strain_species_strain_from_lot_id"
FROM "public"."v_events" base;

CREATE VIEW "public"."vc_locations" AS SELECT * FROM "public"."v_locations";

CREATE VIEW "public"."vc_sterilization_runs" AS
SELECT base.*,
  (SELECT COALESCE(array_agg(btbl."default_unit_size"::text ORDER BY btbl."default_unit_size"::text) FILTER (WHERE btbl."default_unit_size" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_sterilization_runs_items_planned_item" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."sterilization_runs_id" = base.nocopk) AS "default_unit_size_from_planned_item",
  (SELECT COALESCE(array_agg(btbl."item_id"::text ORDER BY btbl."item_id"::text) FILTER (WHERE btbl."item_id" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_sterilization_runs_items_planned_item" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."sterilization_runs_id" = base.nocopk) AS "planned_item_id",
  (SELECT COALESCE(array_agg(btbl."name"::text ORDER BY btbl."name"::text) FILTER (WHERE btbl."name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_sterilization_runs_items_planned_item" j JOIN "public"."items" btbl ON btbl.nocopk = j."items_id" WHERE j."sterilization_runs_id" = base.nocopk) AS "planned_item_name",
  (SELECT COALESCE(array_agg(btbl."recipe_id"::text ORDER BY btbl."recipe_id"::text) FILTER (WHERE btbl."recipe_id" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_sterilization_runs_recipes_planned_recipe" j JOIN "public"."recipes" btbl ON btbl.nocopk = j."recipes_id" WHERE j."sterilization_runs_id" = base.nocopk) AS "recipe_id_from_planned_recipe",
  (SELECT COALESCE(array_agg(btbl."name"::text ORDER BY btbl."name"::text) FILTER (WHERE btbl."name" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_sterilization_runs_recipes_planned_recipe" j JOIN "public"."recipes" btbl ON btbl.nocopk = j."recipes_id" WHERE j."sterilization_runs_id" = base.nocopk) AS "name_from_planned_recipe"
FROM "public"."v_sterilization_runs" base;

CREATE VIEW "public"."vc_print_queue" AS
SELECT base.*,
  (SELECT COALESCE(array_agg(btbl."item_category_mat"::text ORDER BY btbl."item_category_mat"::text) FILTER (WHERE btbl."item_category_mat" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_print_queue_lots_lot_id" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots_id" WHERE j."print_queue_id" = base.nocopk) AS "item_category_mat_from_lot_id",
  '{}'::text[] AS "public_link_from_lot_id",
  '{}'::text[] AS "label_company_lot_from_lot_id",
  (SELECT COALESCE(array_agg(btbl."item_category_mat"::text ORDER BY btbl."item_category_mat"::text) FILTER (WHERE btbl."item_category_mat" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_print_queue_products_product_id" j JOIN "public"."products" btbl ON btbl.nocopk = j."products_id" WHERE j."print_queue_id" = base.nocopk) AS "item_category_mat_from_product_id",
  '{}'::text[] AS "public_link_from_product_id",
  '{}'::text[] AS "label_substrateinputblocks_line_from_lot_id",
  '{}'::text[] AS "label_graininputblocks_line_from_lot_id",
  '{}'::text[] AS "label_footer_lot_from_lot_id",
  '{}'::text[] AS "label_subtitle_lot_from_lot_id",
  '{}'::text[] AS "label_title_lot_from_lot_id",
  (SELECT COALESCE(array_agg(btbl."label_template"::text ORDER BY btbl."label_template"::text) FILTER (WHERE btbl."label_template" IS NOT NULL), '{}'::text[]) FROM "public"."_m2m_print_queue_lots_lot_id" j JOIN "public"."lots" btbl ON btbl.nocopk = j."lots_id" WHERE j."print_queue_id" = base.nocopk) AS "label_template_from_lot_id",
  '{}'::text[] AS "label_useby_line_from_lot_id",
  '{}'::text[] AS "label_spawned_line_from_lot_id",
  '{}'::text[] AS "label_inoc_line_from_lot_id",
  '{}'::text[] AS "label_proc_line_from_lot_id",
  '{}'::text[] AS "label_company_prod_from_product_id",
  '{}'::text[] AS "label_title_prod_from_product_id",
  '{}'::text[] AS "label_subtitle_prod_from_product_id",
  '{}'::text[] AS "label_footer_prod_from_product_id",
  '{}'::text[] AS "label_cottage_prod_from_product_id",
  '{}'::text[] AS "label_companyinfo_prod_from_product_id",
  '{}'::text[] AS "label_disclaimer_prod_from_product_id",
  '{}'::text[] AS "label_companyaddress_prod_from_product_id",
  '{}'::text[] AS "label_packaged_prod_from_product_id",
  '{}'::text[] AS "label_useby_prod_from_product_id",
  '{}'::text[] AS "label_proc_prod_from_product_id",
  '{}'::text[] AS "label_spawned_prod_from_product_id",
  '{}'::text[] AS "label_inoc_prod_from_product_id"
FROM "public"."v_print_queue" base;

CREATE VIEW "public"."vc_ecommerce" AS
SELECT base.*,
  '{}'::text[] AS "available_from_products",
  '{}'::text[] AS "available_from_lots"
FROM "public"."v_ecommerce" base;

CREATE VIEW "public"."vc_ecommerce_orders" AS SELECT * FROM "public"."v_ecommerce_orders";

COMMIT;
