-- Generated by airtable_export_to_postgres_sql.js
-- 2026-01-25T17:35:46.595Z
\set ON_ERROR_STOP on
BEGIN;
SET search_path TO "public";
\copy "strains"("airtable_id","airtable_createdtime","regulated","species_strain","strain_id") FROM 'csv/strains.csv' WITH (FORMAT csv, HEADER true);
\copy "recipes"("airtable_id","airtable_createdtime","category","ingredients","name","recipe_id") FROM 'csv/recipes.csv' WITH (FORMAT csv, HEADER true);
\copy "items"("airtable_id","airtable_createdtime","category","default_unit_size","default_unit_size_lb","item_id","name") FROM 'csv/items.csv' WITH (FORMAT csv, HEADER true);
\copy "locations"("airtable_id","airtable_createdtime","name") FROM 'csv/locations.csv' WITH (FORMAT csv, HEADER true);
\copy "ecommerce"("airtable_id","airtable_createdtime","available_from_lots","available_from_products","item_id","name","status","sync_to_ecwid") FROM 'csv/ecommerce.csv' WITH (FORMAT csv, HEADER true);
COMMIT;
