-- Generated by airtable_export_to_postgres_sql.js
-- 2026-04-19T19:59:35.095Z
SET client_min_messages TO WARNING;
\set ON_ERROR_STOP on
BEGIN;
SET search_path TO "public";
\copy "strains"("airtable_id","strain_id","active","species_strain","regulated") FROM csv/strains.csv WITH (FORMAT csv, HEADER true);
\copy "recipes"("airtable_id","recipe_id","active","name","category","ingredients","notes") FROM csv/recipes.csv WITH (FORMAT csv, HEADER true);
\copy "products"("airtable_id","name_mat","item_category_mat","net_weight_g","net_weight_oz","net_volume_ml","pack_date","use_by","package_size_g","package_count","action","origin_lot_ids_json","process_type_mat","ui_error","ui_error_at","tray_state","notes") FROM csv/products.csv WITH (FORMAT csv, HEADER true);
\copy "lots"("airtable_id","item_name_mat","qty","unit_size","status","parents_json","operator","created_at","use_by","action","item_category_mat","process_type_mat","strain_species_strain_mat","vendor_name_mat","lc_volume_ml","output_count","fruiting_goal","flush_no","harvest_weight_g","notes","syringe_count","source_type","vendor_name","vendor_batch","received_date","total_volume_ml","ui_error","ui_error_at","remaining_volume_ml","fresh_tray_count","frozen_tray_count","casing_applied_at","casing_notes","casing_qty_used_g","label_template","override_inoc_time","inoculated_at","override_spawn_time","spawned_at","sterilized_at","plate_count","plate_group_id","retired_at") FROM csv/lots.csv WITH (FORMAT csv, HEADER true);
\copy "items"("airtable_id","item_id","active","name","category","default_unit_size_lb","default_unit_size_ml","default_unit_size_oz","default_unit_size_g","default_unit_size") FROM csv/items.csv WITH (FORMAT csv, HEADER true);
\copy "events"("airtable_id","type","timestamp","operator","station","fields_json","lots") FROM csv/events.csv WITH (FORMAT csv, HEADER true);
\copy "locations"("airtable_id","name","active","type","notes") FROM csv/locations.csv WITH (FORMAT csv, HEADER true);
\copy "sterilization_runs"("airtable_id","start_time","end_time","operator","planned_count","good_count","destroyed_count","planned_unit_size","ui_error","ui_error_at","process_type","target_temp_c","pressure_mode","override_end_time") FROM csv/sterilization_runs.csv WITH (FORMAT csv, HEADER true);
\copy "print_queue"("airtable_id","source_kind","print_status","label_type","error_msg","created_at","claimed_by","claimed_at","printed_by","printed_at","pdf_path") FROM csv/print_queue.csv WITH (FORMAT csv, HEADER true);
\copy "ecommerce"("airtable_id","name","status","ecwid_sku","sync_to_ecwid","notes","ecwid_category","ecwid_price","ecwid_stock","ecwid_url","ecwid_image","ecwid_upc") FROM csv/ecommerce.csv WITH (FORMAT csv, HEADER true);
\copy "ecommerce_orders"("airtable_id","name","ecwid_order_id","order_number","order_code","status","order_date","customer_name","customer_email","items_json","ecwid_skus","payment_status","payment_method","subtotal","tax_total","order_total","currency","clover_reconciliation_status","clover_payment_id","clover_payment_amount","clover_payment_time","clover_match_confidence","reconciled_at","reconciliation_notes","ecwid_event_type","ecwid_event_id","last_webhook_at") FROM csv/ecommerce_orders.csv WITH (FORMAT csv, HEADER true);

-- Link field: strains.lots -> lots
CREATE TEMP TABLE "_m2m_strains_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_strains_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_strains_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_strains_lots_lots"("strains_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_strains_lots_lots__raw" r
JOIN "strains" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_strains_lots_lots__raw";

-- Link field: strains.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_strains_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_strains_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_strains_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_strains_ecommerce_ecommerce"("strains_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_strains_ecommerce_ecommerce__raw" r
JOIN "strains" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_strains_ecommerce_ecommerce__raw";

-- Link field: strains.products -> products
CREATE TEMP TABLE "_m2m_strains_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_strains_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_strains_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_strains_products_products"("strains_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_strains_products_products__raw" r
JOIN "strains" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_strains_products_products__raw";

-- Link field: recipes.lots -> lots
CREATE TEMP TABLE "_m2m_recipes_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_recipes_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_recipes_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_recipes_lots_lots"("recipes_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_recipes_lots_lots__raw" r
JOIN "recipes" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_recipes_lots_lots__raw";

-- Link field: recipes.sterilization_runs -> sterilization_runs
CREATE TEMP TABLE "_m2m_recipes_sterilization_runs_sterilization_runs__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_recipes_sterilization_runs_sterilization_runs__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_recipes_sterilization_runs_sterilization_runs__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_recipes_sterilization_runs_sterilization_runs"("recipes_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_recipes_sterilization_runs_sterilization_runs__raw" r
JOIN "recipes" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_recipes_sterilization_runs_sterilization_runs__raw";

-- Link field: products.item_id -> items
CREATE TEMP TABLE "_m2m_products_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_items_item_id"("products_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_items_item_id__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_items_item_id__raw";

-- Link field: products.package_item -> items
CREATE TEMP TABLE "_m2m_products_items_package_item__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_items_package_item__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_items_package_item__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_items_package_item"("products_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_items_package_item__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_items_package_item__raw";

-- Link field: products.storage_location -> locations
CREATE TEMP TABLE "_m2m_products_locations_storage_location__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_locations_storage_location__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_locations_storage_location__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_locations_storage_location"("products_id", "locations_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_locations_storage_location__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "locations" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_locations_storage_location__raw";

-- Link field: products.merge_tray_products -> products
CREATE TEMP TABLE "_m2m_products_products_merge_tray_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_products_merge_tray_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_products_merge_tray_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_products_merge_tray_products"("products_id", "products1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_products_merge_tray_products__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_products_merge_tray_products__raw";

-- Link field: products.origin_lots -> lots
CREATE TEMP TABLE "_m2m_products_lots_origin_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_lots_origin_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_lots_origin_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_lots_origin_lots"("products_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_lots_origin_lots__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_lots_origin_lots__raw";

-- Link field: products.strain_id -> strains
CREATE TEMP TABLE "_m2m_products_strains_strain_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_strains_strain_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_strains_strain_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_strains_strain_id"("products_id", "strains_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_strains_strain_id__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "strains" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_strains_strain_id__raw";

-- Link field: products.print_queue -> print_queue
CREATE TEMP TABLE "_m2m_products_print_queue_print_queue__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_print_queue_print_queue__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_print_queue_print_queue__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_print_queue_print_queue"("products_id", "print_queue_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_print_queue_print_queue__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "print_queue" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_print_queue_print_queue__raw";

-- Link field: products.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_products_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_ecommerce_ecommerce"("products_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_ecommerce_ecommerce__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_ecommerce_ecommerce__raw";

-- Link field: lots.item_id -> items
CREATE TEMP TABLE "_m2m_lots_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_items_item_id"("lots_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_items_item_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_items_item_id__raw";

-- Link field: lots.recipe_id -> recipes
CREATE TEMP TABLE "_m2m_lots_recipes_recipe_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_recipes_recipe_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_recipes_recipe_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_recipes_recipe_id"("lots_id", "recipes_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_recipes_recipe_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "recipes" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_recipes_recipe_id__raw";

-- Link field: lots.strain_id -> strains
CREATE TEMP TABLE "_m2m_lots_strains_strain_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_strains_strain_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_strains_strain_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_strains_strain_id"("lots_id", "strains_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_strains_strain_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "strains" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_strains_strain_id__raw";

-- Link field: lots.steri_run_id -> sterilization_runs
CREATE TEMP TABLE "_m2m_lots_sterilization_runs_steri_run_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_sterilization_runs_steri_run_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_sterilization_runs_steri_run_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_sterilization_runs_steri_run_id"("lots_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_sterilization_runs_steri_run_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_sterilization_runs_steri_run_id__raw";

-- Link field: lots.location_id -> locations
CREATE TEMP TABLE "_m2m_lots_locations_location_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_locations_location_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_locations_location_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_locations_location_id"("lots_id", "locations_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_locations_location_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "locations" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_locations_location_id__raw";

-- Link field: lots.events -> events
CREATE TEMP TABLE "_m2m_lots_events_events__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_events_events__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_events_events__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_events_events"("lots_id", "events_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_events_events__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "events" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_events_events__raw";

-- Link field: lots.substrate_inputs -> lots
CREATE TEMP TABLE "_m2m_lots_lots_substrate_inputs__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_lots_substrate_inputs__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_lots_substrate_inputs__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_lots_substrate_inputs"("lots_id", "lots1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_lots_substrate_inputs__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_lots_substrate_inputs__raw";

-- Link field: lots.harvest_item -> items
CREATE TEMP TABLE "_m2m_lots_items_harvest_item__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_items_harvest_item__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_items_harvest_item__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_items_harvest_item"("lots_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_items_harvest_item__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_items_harvest_item__raw";

-- Link field: lots.products -> products
CREATE TEMP TABLE "_m2m_lots_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_products_products"("lots_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_products_products__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_products_products__raw";

-- Link field: lots.print_queue -> print_queue
CREATE TEMP TABLE "_m2m_lots_print_queue_print_queue__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_print_queue_print_queue__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_print_queue_print_queue__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_print_queue_print_queue"("lots_id", "print_queue_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_print_queue_print_queue__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "print_queue" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_print_queue_print_queue__raw";

-- Link field: lots.source_lot_id -> lots
CREATE TEMP TABLE "_m2m_lots_lots_source_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_lots_source_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_lots_source_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_lots_source_lot_id"("lots_id", "lots1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_lots_source_lot_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_lots_source_lot_id__raw";

-- Link field: lots.parent_lot_id -> lots
CREATE TEMP TABLE "_m2m_lots_lots_parent_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_lots_parent_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_lots_parent_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_lots_parent_lot_id"("lots_id", "lots1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_lots_parent_lot_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_lots_parent_lot_id__raw";

-- Link field: lots.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_lots_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_ecommerce_ecommerce"("lots_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_ecommerce_ecommerce__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_ecommerce_ecommerce__raw";

-- Link field: items.lots -> lots
CREATE TEMP TABLE "_m2m_items_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_lots_lots"("items_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_lots_lots__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_lots_lots__raw";

-- Link field: items.sterilization_runs -> sterilization_runs
CREATE TEMP TABLE "_m2m_items_sterilization_runs_sterilization_runs__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_sterilization_runs_sterilization_runs__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_sterilization_runs_sterilization_runs__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_sterilization_runs_sterilization_runs"("items_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_sterilization_runs_sterilization_runs__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_sterilization_runs_sterilization_runs__raw";

-- Link field: items.products -> products
CREATE TEMP TABLE "_m2m_items_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_products_products"("items_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_products_products__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_products_products__raw";

-- Link field: items.lots 4 -> lots
CREATE TEMP TABLE "_m2m_items_lots_lots_4__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_lots_lots_4__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_lots_lots_4__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_lots_lots_4"("items_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_lots_lots_4__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_lots_lots_4__raw";

-- Link field: items.products 2 -> products
CREATE TEMP TABLE "_m2m_items_products_products_2__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_products_products_2__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_products_products_2__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_products_products_2"("items_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_products_products_2__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_products_products_2__raw";

-- Link field: items.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_items_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_ecommerce_ecommerce"("items_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_ecommerce_ecommerce__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_ecommerce_ecommerce__raw";

-- Link field: events.lot_id -> lots
CREATE TEMP TABLE "_m2m_events_lots_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_events_lots_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_events_lots_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_events_lots_lot_id"("events_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_events_lots_lot_id__raw" r
JOIN "events" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_events_lots_lot_id__raw";

-- Link field: locations.lots -> lots
CREATE TEMP TABLE "_m2m_locations_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_locations_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_locations_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_locations_lots_lots"("locations_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_locations_lots_lots__raw" r
JOIN "locations" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_locations_lots_lots__raw";

-- Link field: locations.products -> products
CREATE TEMP TABLE "_m2m_locations_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_locations_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_locations_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_locations_products_products"("locations_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_locations_products_products__raw" r
JOIN "locations" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_locations_products_products__raw";

-- Link field: sterilization_runs.planned_item -> items
CREATE TEMP TABLE "_m2m_sterilization_runs_items_planned_item__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_items_planned_item__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_items_planned_item__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_items_planned_item"("sterilization_runs_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_items_planned_item__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_sterilization_runs_items_planned_item__raw";

-- Link field: sterilization_runs.planned_recipe -> recipes
CREATE TEMP TABLE "_m2m_sterilization_runs_recipes_planned_recipe__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_recipes_planned_recipe__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_recipes_planned_recipe__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_recipes_planned_recipe"("sterilization_runs_id", "recipes_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_recipes_planned_recipe__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "recipes" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_sterilization_runs_recipes_planned_recipe__raw";

-- Link field: sterilization_runs.lots -> lots
CREATE TEMP TABLE "_m2m_sterilization_runs_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_lots_lots"("sterilization_runs_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_lots_lots__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_sterilization_runs_lots_lots__raw";

-- Link field: sterilization_runs.print_queue -> print_queue
CREATE TEMP TABLE "_m2m_sterilization_runs_print_queue_print_queue__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_print_queue_print_queue__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_print_queue_print_queue__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_print_queue_print_queue"("sterilization_runs_id", "print_queue_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_print_queue_print_queue__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "print_queue" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_sterilization_runs_print_queue_print_queue__raw";

-- Link field: print_queue.lot_id -> lots
CREATE TEMP TABLE "_m2m_print_queue_lots_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_print_queue_lots_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_print_queue_lots_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_print_queue_lots_lot_id"("print_queue_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_print_queue_lots_lot_id__raw" r
JOIN "print_queue" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_print_queue_lots_lot_id__raw";

-- Link field: print_queue.product_id -> products
CREATE TEMP TABLE "_m2m_print_queue_products_product_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_print_queue_products_product_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_print_queue_products_product_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_print_queue_products_product_id"("print_queue_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_print_queue_products_product_id__raw" r
JOIN "print_queue" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_print_queue_products_product_id__raw";

-- Link field: print_queue.run_id -> sterilization_runs
CREATE TEMP TABLE "_m2m_print_queue_sterilization_runs_run_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_print_queue_sterilization_runs_run_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_print_queue_sterilization_runs_run_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_print_queue_sterilization_runs_run_id"("print_queue_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_print_queue_sterilization_runs_run_id__raw" r
JOIN "print_queue" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_print_queue_sterilization_runs_run_id__raw";

-- Link field: ecommerce.item_id -> items
CREATE TEMP TABLE "_m2m_ecommerce_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_items_item_id"("ecommerce_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_items_item_id__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_items_item_id__raw";

-- Link field: ecommerce.strain_id -> strains
CREATE TEMP TABLE "_m2m_ecommerce_strains_strain_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_strains_strain_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_strains_strain_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_strains_strain_id"("ecommerce_id", "strains_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_strains_strain_id__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "strains" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_strains_strain_id__raw";

-- Link field: ecommerce.products -> products
CREATE TEMP TABLE "_m2m_ecommerce_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_products_products"("ecommerce_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_products_products__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_products_products__raw";

-- Link field: ecommerce.lots -> lots
CREATE TEMP TABLE "_m2m_ecommerce_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_lots_lots"("ecommerce_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_lots_lots__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_lots_lots__raw";

-- Link field: ecommerce.ecommerce_orders -> ecommerce_orders
CREATE TEMP TABLE "_m2m_ecommerce_ecommerce_orders_ecommerce_orders__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_ecommerce_orders_ecommerce_orders__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_ecommerce_orders_ecommerce_orders__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_ecommerce_orders_ecommerce_orders"("ecommerce_id", "ecommerce_orders_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_ecommerce_orders_ecommerce_orders__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce_orders" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_ecommerce_orders_ecommerce_orders__raw";

-- Link field: ecommerce_orders.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_ecommerce_orders_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_orders_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_orders_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_orders_ecommerce_ecommerce"("ecommerce_orders_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_orders_ecommerce_ecommerce__raw" r
JOIN "ecommerce_orders" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_orders_ecommerce_ecommerce__raw";
COMMIT;
