BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS "public";

-- Table: strains
CREATE TABLE IF NOT EXISTS "public"."strains" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "strain_id" text,
  "species_strain" text,
  "regulated" boolean,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: recipes
CREATE TABLE IF NOT EXISTS "public"."recipes" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "recipe_id" text,
  "name" text,
  "category" text,
  "ingredients" text,
  "notes" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: products
CREATE TABLE IF NOT EXISTS "public"."products" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "product_id" text,
  "name" jsonb,
  "name_mat" text,
  "item_category" jsonb,
  "item_category_mat" text,
  "net_weight_g" numeric,
  "net_weight_oz" numeric,
  "net_volume_ml" numeric,
  "pack_date" date,
  "use_by" date,
  "public_link" text,
  "name (from package_item)" jsonb,
  "package_item_category" jsonb,
  "unit_lbs" jsonb,
  "unit_size" jsonb,
  "package_size_g" numeric,
  "package_count" numeric,
  "action" text,
  "origin_lot_ids_json" text,
  "label_inoc_prod" jsonb,
  "label_spawned_prod" jsonb,
  "label_proc_prod" jsonb,
  "process_type" jsonb,
  "species_strain" jsonb,
  "origin_strain_regulated" jsonb,
  "ui_error" text,
  "ui_error_at" timestamptz,
  "tray_state" text,
  "label_company_prod" text,
  "label_companyaddress_prod" text,
  "label_disclaimer_prod" text,
  "label_companyinfo_prod" text,
  "label_cottage_prod" text,
  "label_title_prod" text,
  "label_subtitle_prod" text,
  "label_footer_prod" text,
  "label_packaged_prod" text,
  "label_useby_prod" text,
  "notes" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: lots
CREATE TABLE IF NOT EXISTS "public"."lots" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "lot_id" text,
  "item_name" jsonb,
  "item_name_mat" text,
  "recipe_name" jsonb,
  "regulated (from strain_id)" jsonb,
  "strain_species_strain" jsonb,
  "qty" numeric,
  "unit_size" numeric,
  "status" text,
  "parents_json" text,
  "process_type (from steri_run_id)" jsonb,
  "operator" text,
  "use_by" date,
  "action" text,
  "item_category" jsonb,
  "item_category_mat" text,
  "process_type_mat" text,
  "strain_species_strain (from lc_lot_id)" jsonb,
  "vendor_name (from lc_lot_id)" jsonb,
  "lc_volume_ml" numeric,
  "item_name_mat (from grain_inputs)" jsonb,
  "inoculated_at (from grain_inputs)" jsonb,
  "name (from item_id) (from grain_inputs)" text,
  "process_type_mat (from substrate_inputs)" jsonb,
  "item_name_mat (from substrate_inputs)" jsonb,
  "name (from item_id) (from substrate_inputs)" text,
  "process_type (from steri_run_id) (from substrate_inputs)" text,
  "output_count" numeric,
  "fruiting_goal" text,
  "flush_no" numeric,
  "harvest_weight_g" numeric,
  "notes" text,
  "syringe_count" numeric,
  "source_type" text,
  "vendor_name" text,
  "vendor_batch" text,
  "received_date" date,
  "total_volume_ml" numeric,
  "ui_error" text,
  "ui_error_at" timestamptz,
  "remaining_volume_ml" numeric,
  "harvest_item_category" jsonb,
  "name (from products)" jsonb,
  "category (from item_id) (from products)" jsonb,
  "fresh_tray_count" numeric,
  "frozen_tray_count" numeric,
  "casing_applied_at" timestamptz,
  "casing_notes" text,
  "casing_qty_used_g" numeric,
  "label_company_lot" text,
  "unit_lbs" text,
  "spawned_date" jsonb,
  "label_inoc_line" text,
  "label_spawned_line" text,
  "label_useby_line" text,
  "label_template" text,
  "label_title_lot" text,
  "label_subtitle_lot" text,
  "label_footer_lot" text,
  "label_proc_line" text,
  "label_graininputblocks_line" text,
  "label_substrateinputblocks_line" text,
  "override_inoc_time" timestamptz,
  "inoculated_at" timestamptz,
  "last_inoculation_date" jsonb,
  "override_spawn_time" timestamptz,
  "spawned_at" timestamptz,
  "sterilized_at" timestamptz,
  "public_link" text,
  "public_link_dark_room" text,
  "public_link_fruiting" text,
  "public_link_harvest" text,
  "public_link_spawn_to_bulk" text,
  "public_link_inoculate_flask" text,
  "public_link_inoculate_grain" text,
  "public_link_freeze_dry_package" text,
  "public_link_substrate_package" text,
  "public_link_lot_lineage" text,
  "first_event_date" jsonb,
  "last_event_date" jsonb,
  "plate_count" numeric,
  "plate_group_id" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: items
CREATE TABLE IF NOT EXISTS "public"."items" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "item_id" text,
  "name" text,
  "category" text,
  "default_unit_size_lb" numeric,
  "default_unit_size_ml" numeric,
  "default_unit_size_oz" numeric,
  "default_unit_size_g" numeric,
  "default_unit_size" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: events
CREATE TABLE IF NOT EXISTS "public"."events" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "event_id" text,
  "status (from lot_id)" jsonb,
  "storage_location (from product_id)" jsonb,
  "grain_inputs (from lot_id)" jsonb,
  "substrate_inputs (from lot_id)" jsonb,
  "vendor_name (from lc_lot_id) (from lot_id)" jsonb,
  "strain_species_strain (from lot_id)" jsonb,
  "type" text,
  "timestamp" timestamptz,
  "operator" text,
  "station" text,
  "fields_json" text,
  "event_time_for_rollup" date,
  "lots" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: locations
CREATE TABLE IF NOT EXISTS "public"."locations" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "name" text,
  "type" text,
  "notes" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: sterilization_runs
CREATE TABLE IF NOT EXISTS "public"."sterilization_runs" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "steri_run_id" text,
  "default_unit_size (from planned_item)" jsonb,
  "planned_item_id" jsonb,
  "planned_item_name" jsonb,
  "start_time" timestamptz,
  "end_time" timestamptz,
  "operator" text,
  "recipe_id (from planned_recipe)" jsonb,
  "name (from planned_recipe)" jsonb,
  "planned_count" numeric,
  "good_count" numeric,
  "destroyed_count" numeric,
  "planned_unit_size" numeric,
  "ui_error" text,
  "ui_error_at" timestamptz,
  "process_type" text,
  "target_temp_c" numeric,
  "pressure_mode" text,
  "override_end_time" timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: print_queue
CREATE TABLE IF NOT EXISTS "public"."print_queue" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "print_id" text,
  "source_kind" text,
  "item_category_mat (from lot_id)" jsonb,
  "public_link (from lot_id)" jsonb,
  "label_company_lot (from lot_id)" jsonb,
  "item_category_mat (from product_id)" jsonb,
  "public_link (from product_id)" jsonb,
  "print_status" text,
  "label_type" text,
  "error_msg" text,
  "print_target" text,
  "claimed_by" text,
  "claimed_at" timestamptz,
  "printed_by" text,
  "printed_at" timestamptz,
  "pdf_path" text,
  "label_substrateinputblocks_line (from lot_id)" jsonb,
  "label_graininputblocks_line (from lot_id)" jsonb,
  "label_footer_lot (from lot_id)" jsonb,
  "label_subtitle_lot (from lot_id)" jsonb,
  "label_title_lot (from lot_id)" jsonb,
  "label_template (from lot_id)" jsonb,
  "label_useby_line (from lot_id)" jsonb,
  "label_spawned_line (from lot_id)" jsonb,
  "label_inoc_line (from lot_id)" jsonb,
  "label_proc_line (from lot_id)" jsonb,
  "label_company_prod (from product_id)" jsonb,
  "label_title_prod (from product_id)" jsonb,
  "label_subtitle_prod (from product_id)" jsonb,
  "label_footer_prod (from product_id)" jsonb,
  "label_cottage_prod (from product_id)" jsonb,
  "label_companyinfo_prod (from product_id)" jsonb,
  "label_disclaimer_prod (from product_id)" jsonb,
  "label_companyaddress_prod (from product_id)" jsonb,
  "label_packaged_prod (from product_id)" jsonb,
  "label_useby_prod (from product_id)" jsonb,
  "label_proc_prod (from product_id)" jsonb,
  "label_spawned_prod (from product_id)" jsonb,
  "label_inoc_prod (from product_id)" jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: ecommerce
CREATE TABLE IF NOT EXISTS "public"."ecommerce" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "name" text,
  "status" text,
  "ecwid_sku" text,
  "sync_to_ecwid" boolean,
  "notes" text,
  "ecwid_category" text,
  "ecwid_price" numeric,
  "ecwid_stock" numeric,
  "ecwid_url" text,
  "ecwid_image" jsonb,
  "available_from_products" jsonb,
  "available_from_lots" jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table: ecommerce_orders
CREATE TABLE IF NOT EXISTS "public"."ecommerce_orders" (
  nocopk bigserial PRIMARY KEY,
  nocouuid uuid NOT NULL DEFAULT gen_random_uuid(),
  airtable_id text UNIQUE,
  "name" text,
  "ecwid_order_id" text,
  "order_number" numeric,
  "status" text,
  "order_date" timestamptz,
  "customer_name" text,
  "customer_email" text,
  "items_json" text,
  "ecwid_skus" text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

COMMIT;
