-- Generated by airtable_export_to_postgres_sql.js
-- 2026-07-17T19:11:56.136Z
SET client_min_messages TO WARNING;
\set ON_ERROR_STOP on
BEGIN;
SET search_path TO "public";
\copy "strains"("airtable_id","strain_id","active","species_strain","regulated","product_use") FROM csv/strains.csv WITH (FORMAT csv, HEADER true);
\copy "locations"("airtable_id","name","active","type","notes") FROM csv/locations.csv WITH (FORMAT csv, HEADER true);
\copy "items"("airtable_id","item_id","active","name","category","default_unit_size_lb","default_unit_size_ml","default_unit_size_oz","default_unit_size_g","default_unit_size","deprecated_reason","component_mode","size_source","sort_order") FROM csv/items.csv WITH (FORMAT csv, HEADER true);
\copy "item_recipe_components"("airtable_id","component_id","active","component_set","component_role","unit_size_lb","default_weight_lb","default_percent","sort_order","notes") FROM csv/item_recipe_components.csv WITH (FORMAT csv, HEADER true);
\copy "recipes"("airtable_id","recipe_id","active","name","category","ingredients","notes") FROM csv/recipes.csv WITH (FORMAT csv, HEADER true);
\copy "lot_recipe_components"("airtable_id","lot_recipe_component_id","component_role","component_weight_lb","component_percent","sort_order","notes") FROM csv/lot_recipe_components.csv WITH (FORMAT csv, HEADER true);
\copy "sterilization_runs"("airtable_id","steri_run_id","start_time","end_time","operator","planned_count","good_count","destroyed_count","planned_unit_size","ui_error","ui_error_at","process_type","target_temp_c","pressure_mode","override_end_time","planned_component_set") FROM csv/sterilization_runs.csv WITH (FORMAT csv, HEADER true);
\copy "lots"("airtable_id","lot_id","item_name_mat","qty","unit_size","status","parents_json","operator","created_at","use_by","action","item_category_mat","process_type_mat","strain_species_strain_mat","vendor_name_mat","lc_volume_ml","output_count","fruiting_goal","flush_no","harvest_weight_g","notes","syringe_count","source_type","vendor_name","vendor_batch","received_date","total_volume_ml","ui_error","ui_error_at","remaining_volume_ml","fresh_tray_count","frozen_tray_count","casing_applied_at","casing_notes","casing_qty_used_g","label_template","override_inoc_time","inoculated_at","override_spawn_time","spawned_at","sterilized_at","plate_count","plate_group_id","retired_at","beganfruiting_at","firstharvested_at","lastharvested_at") FROM csv/lots.csv WITH (FORMAT csv, HEADER true);
\copy "products"("airtable_id","product_id","name_mat","item_category_mat","net_weight_g","net_weight_oz","net_volume_ml","pack_date","use_by","package_class","package_size","package_count","action","origin_lot_ids_json","process_type_mat","ui_error","ui_error_at","tray_state","notes","harvest_flush_no","harvest_weight_g","harvested_at","operator") FROM csv/products.csv WITH (FORMAT csv, HEADER true);
\copy "events"("airtable_id","event_id","type","timestamp","operator","station","fields_json","lots") FROM csv/events.csv WITH (FORMAT csv, HEADER true);
\copy "print_queue"("airtable_id","print_id","source_kind","print_status","label_type","error_msg","created_at","claimed_by","claimed_at","printed_by","printed_at","pdf_path") FROM csv/print_queue.csv WITH (FORMAT csv, HEADER true);
\copy "ecommerce"("airtable_id","name","status","ecwid_sku","sync_to_ecwid","notes","ecwid_category","ecwid_price","ecwid_stock","ecwid_url","ecwid_image","ecwid_upc") FROM csv/ecommerce.csv WITH (FORMAT csv, HEADER true);
\copy "ecommerce_orders"("airtable_id","name","ecwid_order_id","order_number","order_code","status","order_date","customer_name","customer_email","items_json","ecwid_skus","payment_status","payment_method","subtotal","tax_total","order_total","currency","clover_reconciliation_status","clover_payment_id","clover_payment_amount","clover_payment_time","clover_match_confidence","reconciled_at","reconciliation_notes","ecwid_event_type","ecwid_event_id","last_webhook_at") FROM csv/ecommerce_orders.csv WITH (FORMAT csv, HEADER true);

-- Link field: strains.lots -> lots
CREATE TEMP TABLE "_m2m_strains_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_strains_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_strains_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_strains_lots_lots"("strains_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_strains_lots_lots__raw" r
JOIN "strains" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_strains_lots_lots__raw";

-- Link field: strains.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_strains_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_strains_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_strains_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_strains_ecommerce_ecommerce"("strains_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_strains_ecommerce_ecommerce__raw" r
JOIN "strains" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_strains_ecommerce_ecommerce__raw";

-- Link field: strains.products -> products
CREATE TEMP TABLE "_m2m_strains_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_strains_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_strains_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_strains_products_products"("strains_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_strains_products_products__raw" r
JOIN "strains" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_strains_products_products__raw";

-- Link field: locations.products -> products
CREATE TEMP TABLE "_m2m_locations_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_locations_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_locations_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_locations_products_products"("locations_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_locations_products_products__raw" r
JOIN "locations" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_locations_products_products__raw";

-- Link field: items.lots -> lots
CREATE TEMP TABLE "_m2m_items_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_lots_lots"("items_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_lots_lots__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_lots_lots__raw";

-- Link field: items.sterilization_runs -> sterilization_runs
CREATE TEMP TABLE "_m2m_items_sterilization_runs_sterilization_runs__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_sterilization_runs_sterilization_runs__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_sterilization_runs_sterilization_runs__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_sterilization_runs_sterilization_runs"("items_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_sterilization_runs_sterilization_runs__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_sterilization_runs_sterilization_runs__raw";

-- Link field: items.products -> products
CREATE TEMP TABLE "_m2m_items_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_products_products"("items_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_products_products__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_products_products__raw";

-- Link field: items.products 2 -> products
CREATE TEMP TABLE "_m2m_items_products_products_2__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_products_products_2__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_products_products_2__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_products_products_2"("items_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_products_products_2__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_products_products_2__raw";

-- Link field: items.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_items_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_ecommerce_ecommerce"("items_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_ecommerce_ecommerce__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_ecommerce_ecommerce__raw";

-- Link field: items.replaced_by_item_id -> items
CREATE TEMP TABLE "_m2m_items_items_replaced_by_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_items_replaced_by_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_items_replaced_by_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_items_replaced_by_item_id"("items_id", "items1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_items_replaced_by_item_id__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_items_items_replaced_by_item_id__raw" r
  JOIN "items" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "items" base
SET "replaced_by_item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_items_items_replaced_by_item_id__raw";

-- Link field: items.items -> items
CREATE TEMP TABLE "_m2m_items_items_items__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_items_items__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_items_items__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_items_items"("items_id", "items1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_items_items__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_items_items__raw";

-- Link field: items.item_recipe_components -> item_recipe_components
CREATE TEMP TABLE "_m2m_items_item_recipe_components_item_recipe_components__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_item_recipe_components_item_recipe_components__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_item_recipe_components_item_recipe_components__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_item_recipe_components_item_recipe_components"("items_id", "item_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_item_recipe_components_item_recipe_components__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "item_recipe_components" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_item_recipe_components_item_recipe_components__raw";

-- Link field: items.lot_recipe_components -> lot_recipe_components
CREATE TEMP TABLE "_m2m_items_lot_recipe_components_lot_recipe_components__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_items_lot_recipe_components_lot_recipe_components__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_items_lot_recipe_components_lot_recipe_components__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_items_lot_recipe_components_lot_recipe_components"("items_id", "lot_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_items_lot_recipe_components_lot_recipe_components__raw" r
JOIN "items" a ON a.airtable_id = r.a_airtable_id
JOIN "lot_recipe_components" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_items_lot_recipe_components_lot_recipe_components__raw";

-- Link field: item_recipe_components.item_id -> items
CREATE TEMP TABLE "_m2m_item_recipe_components_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_item_recipe_components_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_item_recipe_components_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_item_recipe_components_items_item_id"("item_recipe_components_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_item_recipe_components_items_item_id__raw" r
JOIN "item_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_item_recipe_components_items_item_id__raw" r
  JOIN "item_recipe_components" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "item_recipe_components" base
SET "item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_item_recipe_components_items_item_id__raw";

-- Link field: item_recipe_components.recipe_id -> recipes
CREATE TEMP TABLE "_m2m_item_recipe_components_recipes_recipe_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_item_recipe_components_recipes_recipe_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_item_recipe_components_recipes_recipe_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_item_recipe_components_recipes_recipe_id"("item_recipe_components_id", "recipes_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_item_recipe_components_recipes_recipe_id__raw" r
JOIN "item_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "recipes" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_item_recipe_components_recipes_recipe_id__raw" r
  JOIN "item_recipe_components" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "recipes" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "item_recipe_components" base
SET "recipe_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_item_recipe_components_recipes_recipe_id__raw";

-- Link field: item_recipe_components.lot_recipe_components -> lot_recipe_components
CREATE TEMP TABLE "_m2m_item_recipe_components_lot_recipe_components_lo_e568d2b31e"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_item_recipe_components_lot_recipe_components_lo_e568d2b31e"("a_airtable_id","b_airtable_id") FROM csv/_m2m_item_recipe_components_lot_recipe_components_lo_e568d2b31e.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_item_recipe_components_lot_recipe_components_lo_40a5397268"("item_recipe_components_id", "lot_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_item_recipe_components_lot_recipe_components_lo_e568d2b31e" r
JOIN "item_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "lot_recipe_components" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_item_recipe_components_lot_recipe_components_lo_e568d2b31e";

-- Link field: recipes.lots -> lots
CREATE TEMP TABLE "_m2m_recipes_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_recipes_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_recipes_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_recipes_lots_lots"("recipes_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_recipes_lots_lots__raw" r
JOIN "recipes" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_recipes_lots_lots__raw";

-- Link field: recipes.sterilization_runs -> sterilization_runs
CREATE TEMP TABLE "_m2m_recipes_sterilization_runs_sterilization_runs__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_recipes_sterilization_runs_sterilization_runs__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_recipes_sterilization_runs_sterilization_runs__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_recipes_sterilization_runs_sterilization_runs"("recipes_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_recipes_sterilization_runs_sterilization_runs__raw" r
JOIN "recipes" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_recipes_sterilization_runs_sterilization_runs__raw";

-- Link field: recipes.item_recipe_components -> item_recipe_components
CREATE TEMP TABLE "_m2m_recipes_item_recipe_components_item_recipe_components__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_recipes_item_recipe_components_item_recipe_components__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_recipes_item_recipe_components_item_recipe_components__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_recipes_item_recipe_components_item_recipe_components"("recipes_id", "item_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_recipes_item_recipe_components_item_recipe_components__raw" r
JOIN "recipes" a ON a.airtable_id = r.a_airtable_id
JOIN "item_recipe_components" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_recipes_item_recipe_components_item_recipe_components__raw";

-- Link field: recipes.lot_recipe_components -> lot_recipe_components
CREATE TEMP TABLE "_m2m_recipes_lot_recipe_components_lot_recipe_components__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_recipes_lot_recipe_components_lot_recipe_components__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_recipes_lot_recipe_components_lot_recipe_components__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_recipes_lot_recipe_components_lot_recipe_components"("recipes_id", "lot_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_recipes_lot_recipe_components_lot_recipe_components__raw" r
JOIN "recipes" a ON a.airtable_id = r.a_airtable_id
JOIN "lot_recipe_components" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_recipes_lot_recipe_components_lot_recipe_components__raw";

-- Link field: lot_recipe_components.lot_id -> lots
CREATE TEMP TABLE "_m2m_lot_recipe_components_lots_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lot_recipe_components_lots_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lot_recipe_components_lots_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lot_recipe_components_lots_lot_id"("lot_recipe_components_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lot_recipe_components_lots_lot_id__raw" r
JOIN "lot_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lot_recipe_components_lots_lot_id__raw" r
  JOIN "lot_recipe_components" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "lots" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lot_recipe_components" base
SET "lot_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lot_recipe_components_lots_lot_id__raw";

-- Link field: lot_recipe_components.item_id -> items
CREATE TEMP TABLE "_m2m_lot_recipe_components_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lot_recipe_components_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lot_recipe_components_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lot_recipe_components_items_item_id"("lot_recipe_components_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lot_recipe_components_items_item_id__raw" r
JOIN "lot_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lot_recipe_components_items_item_id__raw" r
  JOIN "lot_recipe_components" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lot_recipe_components" base
SET "item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lot_recipe_components_items_item_id__raw";

-- Link field: lot_recipe_components.recipe_id -> recipes
CREATE TEMP TABLE "_m2m_lot_recipe_components_recipes_recipe_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lot_recipe_components_recipes_recipe_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lot_recipe_components_recipes_recipe_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lot_recipe_components_recipes_recipe_id"("lot_recipe_components_id", "recipes_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lot_recipe_components_recipes_recipe_id__raw" r
JOIN "lot_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "recipes" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lot_recipe_components_recipes_recipe_id__raw" r
  JOIN "lot_recipe_components" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "recipes" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lot_recipe_components" base
SET "recipe_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lot_recipe_components_recipes_recipe_id__raw";

-- Link field: lot_recipe_components.source_item_recipe_component -> item_recipe_components
CREATE TEMP TABLE "_m2m_lot_recipe_components_item_recipe_components_so_e0584c69e4"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lot_recipe_components_item_recipe_components_so_e0584c69e4"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lot_recipe_components_item_recipe_components_so_e0584c69e4.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lot_recipe_components_item_recipe_components_so_24cd865945"("lot_recipe_components_id", "item_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lot_recipe_components_item_recipe_components_so_e0584c69e4" r
JOIN "lot_recipe_components" a ON a.airtable_id = r.a_airtable_id
JOIN "item_recipe_components" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lot_recipe_components_item_recipe_components_so_e0584c69e4" r
  JOIN "lot_recipe_components" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "item_recipe_components" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lot_recipe_components" base
SET "source_item_recipe_component_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lot_recipe_components_item_recipe_components_so_e0584c69e4";

-- Link field: sterilization_runs.planned_item -> items
CREATE TEMP TABLE "_m2m_sterilization_runs_items_planned_item__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_items_planned_item__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_items_planned_item__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_items_planned_item"("sterilization_runs_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_items_planned_item__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_sterilization_runs_items_planned_item__raw" r
  JOIN "sterilization_runs" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "sterilization_runs" base
SET "planned_item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_sterilization_runs_items_planned_item__raw";

-- Link field: sterilization_runs.planned_recipe -> recipes
CREATE TEMP TABLE "_m2m_sterilization_runs_recipes_planned_recipe__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_recipes_planned_recipe__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_recipes_planned_recipe__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_recipes_planned_recipe"("sterilization_runs_id", "recipes_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_recipes_planned_recipe__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "recipes" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_sterilization_runs_recipes_planned_recipe__raw" r
  JOIN "sterilization_runs" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "recipes" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "sterilization_runs" base
SET "planned_recipe_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_sterilization_runs_recipes_planned_recipe__raw";

-- Link field: sterilization_runs.lots -> lots
CREATE TEMP TABLE "_m2m_sterilization_runs_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_lots_lots"("sterilization_runs_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_lots_lots__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_sterilization_runs_lots_lots__raw";

-- Link field: sterilization_runs.print_queue -> print_queue
CREATE TEMP TABLE "_m2m_sterilization_runs_print_queue_print_queue__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_sterilization_runs_print_queue_print_queue__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_sterilization_runs_print_queue_print_queue__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_sterilization_runs_print_queue_print_queue"("sterilization_runs_id", "print_queue_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_sterilization_runs_print_queue_print_queue__raw" r
JOIN "sterilization_runs" a ON a.airtable_id = r.a_airtable_id
JOIN "print_queue" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_sterilization_runs_print_queue_print_queue__raw";

-- Link field: lots.item_id -> items
CREATE TEMP TABLE "_m2m_lots_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_items_item_id"("lots_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_items_item_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lots_items_item_id__raw" r
  JOIN "lots" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lots" base
SET "item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lots_items_item_id__raw";

-- Link field: lots.recipe_id -> recipes
CREATE TEMP TABLE "_m2m_lots_recipes_recipe_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_recipes_recipe_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_recipes_recipe_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_recipes_recipe_id"("lots_id", "recipes_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_recipes_recipe_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "recipes" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lots_recipes_recipe_id__raw" r
  JOIN "lots" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "recipes" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lots" base
SET "recipe_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lots_recipes_recipe_id__raw";

-- Link field: lots.strain_id -> strains
CREATE TEMP TABLE "_m2m_lots_strains_strain_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_strains_strain_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_strains_strain_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_strains_strain_id"("lots_id", "strains_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_strains_strain_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "strains" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lots_strains_strain_id__raw" r
  JOIN "lots" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "strains" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lots" base
SET "strain_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lots_strains_strain_id__raw";

-- Link field: lots.steri_run_id -> sterilization_runs
CREATE TEMP TABLE "_m2m_lots_sterilization_runs_steri_run_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_sterilization_runs_steri_run_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_sterilization_runs_steri_run_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_sterilization_runs_steri_run_id"("lots_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_sterilization_runs_steri_run_id__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_lots_sterilization_runs_steri_run_id__raw" r
  JOIN "lots" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "sterilization_runs" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "lots" base
SET "steri_run_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_lots_sterilization_runs_steri_run_id__raw";

-- Link field: lots.events -> events
CREATE TEMP TABLE "_m2m_lots_events_events__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_events_events__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_events_events__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_events_events"("lots_id", "events_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_events_events__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "events" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_events_events__raw";

-- Link field: lots.substrate_inputs -> lots
CREATE TEMP TABLE "_m2m_lots_lots_substrate_inputs__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_lots_substrate_inputs__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_lots_substrate_inputs__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_lots_substrate_inputs"("lots_id", "lots1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_lots_substrate_inputs__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_lots_substrate_inputs__raw";

-- Link field: lots.products -> products
CREATE TEMP TABLE "_m2m_lots_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_products_products"("lots_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_products_products__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_products_products__raw";

-- Link field: lots.print_queue -> print_queue
CREATE TEMP TABLE "_m2m_lots_print_queue_print_queue__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_print_queue_print_queue__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_print_queue_print_queue__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_print_queue_print_queue"("lots_id", "print_queue_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_print_queue_print_queue__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "print_queue" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_print_queue_print_queue__raw";

-- Link field: lots.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_lots_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_ecommerce_ecommerce"("lots_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_ecommerce_ecommerce__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_ecommerce_ecommerce__raw";

-- Link field: lots.lot_recipe_components -> lot_recipe_components
CREATE TEMP TABLE "_m2m_lots_lot_recipe_components_lot_recipe_components__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_lots_lot_recipe_components_lot_recipe_components__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_lots_lot_recipe_components_lot_recipe_components__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_lots_lot_recipe_components_lot_recipe_components"("lots_id", "lot_recipe_components_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_lots_lot_recipe_components_lot_recipe_components__raw" r
JOIN "lots" a ON a.airtable_id = r.a_airtable_id
JOIN "lot_recipe_components" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_lots_lot_recipe_components_lot_recipe_components__raw";

-- Link field: products.item_id -> items
CREATE TEMP TABLE "_m2m_products_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_items_item_id"("products_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_items_item_id__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_products_items_item_id__raw" r
  JOIN "products" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "products" base
SET "item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_products_items_item_id__raw";

-- Link field: products.package_item -> items
CREATE TEMP TABLE "_m2m_products_items_package_item__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_items_package_item__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_items_package_item__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_items_package_item"("products_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_items_package_item__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_products_items_package_item__raw" r
  JOIN "products" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "products" base
SET "package_item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_products_items_package_item__raw";

-- Link field: products.storage_location -> locations
CREATE TEMP TABLE "_m2m_products_locations_storage_location__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_locations_storage_location__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_locations_storage_location__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_locations_storage_location"("products_id", "locations_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_locations_storage_location__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "locations" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_products_locations_storage_location__raw" r
  JOIN "products" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "locations" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "products" base
SET "storage_location_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_products_locations_storage_location__raw";

-- Link field: products.merge_tray_products -> products
CREATE TEMP TABLE "_m2m_products_products_merge_tray_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_products_merge_tray_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_products_merge_tray_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_products_merge_tray_products"("products_id", "products1_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_products_merge_tray_products__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_products_merge_tray_products__raw";

-- Link field: products.origin_lots -> lots
CREATE TEMP TABLE "_m2m_products_lots_origin_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_lots_origin_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_lots_origin_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_lots_origin_lots"("products_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_lots_origin_lots__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_lots_origin_lots__raw";

-- Link field: products.strain_id -> strains
CREATE TEMP TABLE "_m2m_products_strains_strain_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_strains_strain_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_strains_strain_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_strains_strain_id"("products_id", "strains_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_strains_strain_id__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "strains" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_products_strains_strain_id__raw" r
  JOIN "products" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "strains" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "products" base
SET "strain_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_products_strains_strain_id__raw";

-- Link field: products.print_queue -> print_queue
CREATE TEMP TABLE "_m2m_products_print_queue_print_queue__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_print_queue_print_queue__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_print_queue_print_queue__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_print_queue_print_queue"("products_id", "print_queue_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_print_queue_print_queue__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "print_queue" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_print_queue_print_queue__raw";

-- Link field: products.ecommerce -> ecommerce
CREATE TEMP TABLE "_m2m_products_ecommerce_ecommerce__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_products_ecommerce_ecommerce__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_products_ecommerce_ecommerce__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_products_ecommerce_ecommerce"("products_id", "ecommerce_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_products_ecommerce_ecommerce__raw" r
JOIN "products" a ON a.airtable_id = r.a_airtable_id
JOIN "ecommerce" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_products_ecommerce_ecommerce__raw";

-- Link field: events.lot_id -> lots
CREATE TEMP TABLE "_m2m_events_lots_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_events_lots_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_events_lots_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_events_lots_lot_id"("events_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_events_lots_lot_id__raw" r
JOIN "events" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_events_lots_lot_id__raw" r
  JOIN "events" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "lots" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "events" base
SET "lot_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_events_lots_lot_id__raw";

-- Link field: print_queue.lot_id -> lots
CREATE TEMP TABLE "_m2m_print_queue_lots_lot_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_print_queue_lots_lot_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_print_queue_lots_lot_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_print_queue_lots_lot_id"("print_queue_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_print_queue_lots_lot_id__raw" r
JOIN "print_queue" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_print_queue_lots_lot_id__raw" r
  JOIN "print_queue" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "lots" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "print_queue" base
SET "lot_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_print_queue_lots_lot_id__raw";

-- Link field: print_queue.product_id -> products
CREATE TEMP TABLE "_m2m_print_queue_products_product_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_print_queue_products_product_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_print_queue_products_product_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_print_queue_products_product_id"("print_queue_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_print_queue_products_product_id__raw" r
JOIN "print_queue" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_print_queue_products_product_id__raw" r
  JOIN "print_queue" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "products" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "print_queue" base
SET "product_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_print_queue_products_product_id__raw";

-- Link field: print_queue.run_id -> sterilization_runs
CREATE TEMP TABLE "_m2m_print_queue_sterilization_runs_run_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_print_queue_sterilization_runs_run_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_print_queue_sterilization_runs_run_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_print_queue_sterilization_runs_run_id"("print_queue_id", "sterilization_runs_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_print_queue_sterilization_runs_run_id__raw" r
JOIN "print_queue" a ON a.airtable_id = r.a_airtable_id
JOIN "sterilization_runs" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_print_queue_sterilization_runs_run_id__raw" r
  JOIN "print_queue" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "sterilization_runs" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "print_queue" base
SET "run_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_print_queue_sterilization_runs_run_id__raw";

-- Link field: ecommerce.item_id -> items
CREATE TEMP TABLE "_m2m_ecommerce_items_item_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_items_item_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_items_item_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_items_item_id"("ecommerce_id", "items_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_items_item_id__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "items" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_ecommerce_items_item_id__raw" r
  JOIN "ecommerce" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "items" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "ecommerce" base
SET "item_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_ecommerce_items_item_id__raw";

-- Link field: ecommerce.strain_id -> strains
CREATE TEMP TABLE "_m2m_ecommerce_strains_strain_id__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_strains_strain_id__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_strains_strain_id__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_strains_strain_id"("ecommerce_id", "strains_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_strains_strain_id__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "strains" b ON b.airtable_id = r.b_airtable_id;
WITH resolved AS (
  SELECT DISTINCT ON (src."nocopk") src."nocopk" AS "src_nocopk", tgt."nocopk" AS "tgt_nocopk"
  FROM "_m2m_ecommerce_strains_strain_id__raw" r
  JOIN "ecommerce" src ON src."airtable_id" = r."a_airtable_id"
  JOIN "strains" tgt ON tgt."airtable_id" = r."b_airtable_id"
  ORDER BY src."nocopk", tgt."nocopk"
)
UPDATE "ecommerce" base
SET "strain_id" = resolved."tgt_nocopk"
FROM resolved
WHERE base."nocopk" = resolved."src_nocopk";
DROP TABLE "_m2m_ecommerce_strains_strain_id__raw";

-- Link field: ecommerce.products -> products
CREATE TEMP TABLE "_m2m_ecommerce_products_products__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_products_products__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_products_products__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_products_products"("ecommerce_id", "products_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_products_products__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "products" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_products_products__raw";

-- Link field: ecommerce.lots -> lots
CREATE TEMP TABLE "_m2m_ecommerce_lots_lots__raw"("a_airtable_id" text, "b_airtable_id" text);
\copy "_m2m_ecommerce_lots_lots__raw"("a_airtable_id","b_airtable_id") FROM csv/_m2m_ecommerce_lots_lots__raw.csv WITH (FORMAT csv, HEADER true);
INSERT INTO "_m2m_ecommerce_lots_lots"("ecommerce_id", "lots_id")
SELECT a.nocopk, b.nocopk
FROM "_m2m_ecommerce_lots_lots__raw" r
JOIN "ecommerce" a ON a.airtable_id = r.a_airtable_id
JOIN "lots" b ON b.airtable_id = r.b_airtable_id;
DROP TABLE "_m2m_ecommerce_lots_lots__raw";
COMMIT;
