#!/usr/bin/env python3
"""Audit MushroomProcess migration CSVs for Reporting issue #87.

The script intentionally uses only the Python standard library. It reads the
PostgreSQL CSVs generated by airtable_export_to_postgres_sql.js and reports the
historical lifecycle/inventory facts that can safely underpin Reporting.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Iterable

TERMINAL_EVENT_TYPES = {
    "Contaminated",
    "Inviable",
    "Composted",
    "Consumed",
    "Destroyed",
    "Expired",
}

TERMINAL_TRAY_STATE_TOKENS = {
    "emptytray",
    "compost",
    "composted",
    "spoiled",
    "retired",
    "expired",
    "consumed",
    "shipped",
}

TERMINAL_LOCATION_TOKENS = {
    "compost",
    "consumed",
    "expired",
    "retired",
    "shipped",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit generated PostgreSQL migration CSVs for Reporting issue #87."
    )
    parser.add_argument(
        "--csv-dir",
        required=True,
        help="Directory containing lots.csv, events.csv, products.csv and generated _m2m CSVs.",
    )
    parser.add_argument(
        "--as-of",
        help="Inventory expiration date in YYYY-MM-DD form. Defaults to the latest observed data date.",
    )
    parser.add_argument(
        "--format",
        choices=("markdown", "json"),
        default="markdown",
        help="Output format (default: markdown).",
    )
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Required migration CSV not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def text(value: Any) -> str:
    return "" if value is None else str(value).strip()


def nonblank(value: Any) -> bool:
    return text(value) != ""


def parse_dt(value: Any) -> datetime | None:
    raw = text(value)
    if not raw:
        return None
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        try:
            parsed = datetime.combine(date.fromisoformat(raw), datetime.min.time())
        except ValueError:
            return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def parse_date(value: Any) -> date | None:
    raw = text(value)
    if not raw:
        return None
    try:
        return date.fromisoformat(raw[:10])
    except ValueError:
        parsed = parse_dt(raw)
        return parsed.date() if parsed else None


def parse_json_object(value: Any) -> dict[str, Any]:
    raw = text(value)
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def norm_token(value: Any) -> str:
    return re.sub(r"[^a-z0-9]", "", text(value).lower())


def relation_map(rows: Iterable[dict[str, str]]) -> dict[str, list[str]]:
    result: dict[str, list[str]] = defaultdict(list)
    for row in rows:
        left = text(row.get("a_airtable_id"))
        right = text(row.get("b_airtable_id"))
        if left and right:
            result[left].append(right)
    return dict(result)


def first_event_by_lot(
    events: list[dict[str, Any]], event_types: set[str]
) -> dict[str, datetime]:
    result: dict[str, datetime] = {}
    for event in events:
        if event["type"] not in event_types or not event["lot_airtable_id"] or not event["timestamp_dt"]:
            continue
        lot_id = event["lot_airtable_id"]
        t = event["timestamp_dt"]
        if lot_id not in result or t < result[lot_id]:
            result[lot_id] = t
    return result


def last_event_by_lot(
    events: list[dict[str, Any]], event_types: set[str]
) -> dict[str, datetime]:
    result: dict[str, datetime] = {}
    for event in events:
        if event["type"] not in event_types or not event["lot_airtable_id"] or not event["timestamp_dt"]:
            continue
        lot_id = event["lot_airtable_id"]
        t = event["timestamp_dt"]
        if lot_id not in result or t > result[lot_id]:
            result[lot_id] = t
    return result


def coverage(
    lots: list[dict[str, Any]], direct_field: str, event_map: dict[str, datetime]
) -> dict[str, int]:
    direct_ids = {
        row["airtable_id"]
        for row in lots
        if parse_dt(row.get(direct_field)) is not None
    }
    event_ids = set(event_map)
    return {
        "direct": len(direct_ids),
        "event": len(event_ids),
        "both": len(direct_ids & event_ids),
        "direct_only": len(direct_ids - event_ids),
        "event_only": len(event_ids - direct_ids),
        "either": len(direct_ids | event_ids),
    }


def pct(n: int, d: int) -> str:
    return "0.0%" if not d else f"{100.0 * n / d:.1f}%"


def infer_as_of(
    lots: list[dict[str, Any]], events: list[dict[str, Any]], products: list[dict[str, Any]]
) -> date:
    candidates: list[date] = []
    for row in lots:
        value = parse_dt(row.get("created_at"))
        if value:
            candidates.append(value.date())
    for event in events:
        value = event.get("timestamp_dt")
        if value:
            candidates.append(value.date())
    for row in products:
        value = parse_date(row.get("pack_date"))
        if value:
            candidates.append(value)
    if not candidates:
        raise ValueError("Could not infer an as-of date from migration data")
    return max(candidates)


def build_audit(csv_dir: Path, as_of: date | None) -> dict[str, Any]:
    lots = read_csv(csv_dir / "lots.csv")
    raw_events = read_csv(csv_dir / "events.csv")
    products = read_csv(csv_dir / "products.csv")
    locations = read_csv(csv_dir / "locations.csv")

    event_lot_rel = relation_map(read_csv(csv_dir / "_m2m_events_lots_lot_id__raw.csv"))
    grain_rel = relation_map(read_csv(csv_dir / "_m2m_lots_lots_grain_inputs__raw.csv"))
    substrate_rel = relation_map(read_csv(csv_dir / "_m2m_lots_lots_substrate_inputs__raw.csv"))
    lot_product_rel = relation_map(read_csv(csv_dir / "_m2m_lots_products_products__raw.csv"))
    product_origin_rel = relation_map(read_csv(csv_dir / "_m2m_products_lots_origin_lots__raw.csv"))
    lot_strain_rel = relation_map(read_csv(csv_dir / "_m2m_lots_strains_strain_id__raw.csv"))
    product_location_rel = relation_map(read_csv(csv_dir / "_m2m_products_locations_storage_location__raw.csv"))

    lots_by_id = {row["airtable_id"]: row for row in lots}
    products_by_id = {row["airtable_id"]: row for row in products}
    locations_by_id = {row["airtable_id"]: row for row in locations}

    events: list[dict[str, Any]] = []
    for row in raw_events:
        linked = event_lot_rel.get(row["airtable_id"], [])
        events.append(
            {
                **row,
                "type": text(row.get("type")),
                "timestamp_dt": parse_dt(row.get("timestamp")),
                "lot_airtable_id": linked[0] if linked else "",
                "fields": parse_json_object(row.get("fields_json")),
            }
        )

    as_of = as_of or infer_as_of(lots, events, products)

    ster_events = first_event_by_lot(events, {"Sterilized", "Pasteurized"})
    inoc_events = first_event_by_lot(events, {"Inoculated"})
    fully_events = first_event_by_lot(events, {"FullyColonized"})
    spawn_events = first_event_by_lot(events, {"SpawnedToBulk"})
    fruit_events = first_event_by_lot(events, {"FruitingStart", "StartFruiting", "StartedFruiting"})
    harvest_first_events = first_event_by_lot(events, {"Harvest"})
    harvest_last_events = last_event_by_lot(events, {"Harvest"})
    contam_events = first_event_by_lot(events, {"Contaminated"})
    terminal_events = last_event_by_lot(events, TERMINAL_EVENT_TYPES)

    event_types = Counter(event["type"] or "(blank)" for event in events)

    milestone_coverage = {
        "processed_at": coverage(lots, "sterilized_at", ster_events),
        "inoculated_at": coverage(lots, "inoculated_at", inoc_events),
        "spawned_at": coverage(lots, "spawned_at", spawn_events),
        "fruiting_start_at": coverage(lots, "beganfruiting_at", fruit_events),
        "first_harvest_at": coverage(lots, "firstharvested_at", harvest_first_events),
        "last_harvest_at": coverage(lots, "lastharvested_at", harvest_last_events),
        "terminal_at": coverage(lots, "retired_at", terminal_events),
    }

    # Direct/event timestamp agreement for milestones where both historical sources exist.
    agreement: dict[str, dict[str, int]] = {}
    for name, direct_field, event_map in (
        ("processed_at", "sterilized_at", ster_events),
        ("inoculated_at", "inoculated_at", inoc_events),
        ("spawned_at", "spawned_at", spawn_events),
        ("terminal_at", "retired_at", terminal_events),
    ):
        both = 0
        within_60s = 0
        within_1d = 0
        for lot in lots:
            direct = parse_dt(lot.get(direct_field))
            event = event_map.get(lot["airtable_id"])
            if direct and event:
                both += 1
                seconds = abs((direct - event).total_seconds())
                if seconds <= 60:
                    within_60s += 1
                if seconds <= 86400:
                    within_1d += 1
        agreement[name] = {
            "both": both,
            "within_60_seconds": within_60s,
            "within_1_day": within_1d,
        }

    fruiting_blocks = [row for row in lots if text(row.get("item_category_mat")) == "fruiting_block"]
    grain_lots = [row for row in lots if text(row.get("item_category_mat")) == "grain"]

    # Canonical event/direct hybrid timestamps used only for audit readiness measurements.
    def hybrid_time(lot_airtable_id: str, direct_field: str, event_map: dict[str, datetime]) -> datetime | None:
        direct = parse_dt(lots_by_id[lot_airtable_id].get(direct_field))
        return direct or event_map.get(lot_airtable_id)

    grain_age_samples = 0
    downstream_contam_samples = 0
    substrate_age_blocks = 0
    for block in fruiting_blocks:
        block_id = block["airtable_id"]
        block_spawn = hybrid_time(block_id, "spawned_at", spawn_events)
        grain_inputs = grain_rel.get(block_id, [])
        if block_spawn and grain_inputs:
            grain = grain_inputs[0]
            grain_inoc = hybrid_time(grain, "inoculated_at", inoc_events)
            if grain_inoc and block_spawn >= grain_inoc:
                grain_age_samples += 1
                if block_id in contam_events:
                    downstream_contam_samples += 1

        substrate_inputs = substrate_rel.get(block_id, [])
        if block_spawn and substrate_inputs:
            all_ready = True
            for substrate in substrate_inputs:
                substrate_processed = hybrid_time(substrate, "sterilized_at", ster_events)
                if not substrate_processed:
                    all_ready = False
                    break
            if all_ready:
                substrate_age_blocks += 1

    grain_self_contam = sum(1 for row in grain_lots if row["airtable_id"] in contam_events)
    grain_with_inoc = sum(
        1
        for row in grain_lots
        if hybrid_time(row["airtable_id"], "inoculated_at", inoc_events)
    )
    grain_inoc_to_contam = sum(
        1
        for row in grain_lots
        if hybrid_time(row["airtable_id"], "inoculated_at", inoc_events)
        and row["airtable_id"] in contam_events
    )

    harvest_events = [event for event in events if event["type"] == "Harvest" and event["lot_airtable_id"]]
    harvest_lots = {event["lot_airtable_id"] for event in harvest_events}
    flush_groups: Counter[tuple[str, str]] = Counter()
    flushes_by_lot: dict[str, set[int]] = defaultdict(set)
    harvest_product_refs: set[str] = set()
    for event in harvest_events:
        fields = event["fields"]
        flush_raw = fields.get("flush_no")
        if flush_raw is not None:
            flush_key = text(flush_raw)
            flush_groups[(event["lot_airtable_id"], flush_key)] += 1
            try:
                flushes_by_lot[event["lot_airtable_id"]].add(int(flush_raw))
            except (TypeError, ValueError):
                pass
        refs: list[Any] = []
        if "created_product_ids" in fields:
            value = fields["created_product_ids"]
            refs = value if isinstance(value, list) else [value]
        elif "created_product_id" in fields:
            refs = [fields["created_product_id"]]
        for ref in refs:
            if text(ref):
                harvest_product_refs.add(text(ref))

    duplicate_flush_groups = sum(1 for count in flush_groups.values() if count > 1)
    noncontiguous_flush_lots = 0
    for values in flushes_by_lot.values():
        if values and sorted(values) != list(range(1, max(values) + 1)):
            noncontiguous_flush_lots += 1

    tray_products = [
        row
        for row in products
        if text(row.get("item_category_mat")) in {"freezer_tray", "fresh_tray"}
    ]
    tray_products_recoverable = sum(
        1 for row in tray_products if row["airtable_id"] in harvest_product_refs
    )

    # "Record creation" is not physical inception for backfilled Airtable records.
    precreated_lots = 0
    precreated_30d = 0
    event_times_by_lot: dict[str, list[datetime]] = defaultdict(list)
    for event in events:
        if event["lot_airtable_id"] and event["timestamp_dt"]:
            event_times_by_lot[event["lot_airtable_id"]].append(event["timestamp_dt"])
    for lot in lots:
        created = parse_dt(lot.get("created_at"))
        candidates = [
            parse_dt(lot.get("received_date")),
            parse_dt(lot.get("sterilized_at")),
            parse_dt(lot.get("inoculated_at")),
            parse_dt(lot.get("spawned_at")),
            parse_dt(lot.get("casing_applied_at")),
        ]
        candidates.extend(event_times_by_lot.get(lot["airtable_id"], []))
        candidates = [candidate for candidate in candidates if candidate]
        if created and candidates:
            earliest = min(candidates)
            delta_days = (created - earliest).total_seconds() / 86400.0
            if delta_days > 1:
                precreated_lots += 1
            if delta_days > 30:
                precreated_30d += 1

    orphan_events = [event for event in events if not event["lot_airtable_id"]]
    orphan_types = Counter(event["type"] or "(blank)" for event in orphan_events)
    undated_events = [event for event in events if not event["timestamp_dt"]]
    undated_types = Counter(event["type"] or "(blank)" for event in undated_events)
    lots_with_event_relation = {event["lot_airtable_id"] for event in events if event["lot_airtable_id"]}
    lots_without_event_relation = sum(1 for row in lots if row["airtable_id"] not in lots_with_event_relation)
    lots_without_dated_event = sum(1 for row in lots if row["airtable_id"] not in event_times_by_lot)

    # Historical inventory snapshot uses the active-product rule currently used by Products_qProducts.
    location_for_product: dict[str, str] = {}
    for product_id, linked in product_location_rel.items():
        if linked:
            location_for_product[product_id] = text(locations_by_id.get(linked[0], {}).get("name"))

    active_products = 0
    active_expired = 0
    active_unknown_location = 0
    use_by_before_pack = 0
    for product in products:
        state_tokens = [norm_token(part) for part in re.split(r"[,;|]+", text(product.get("tray_state")))]
        state_is_terminal = any(token in TERMINAL_TRAY_STATE_TOKENS for token in state_tokens if token)
        location_name = location_for_product.get(product["airtable_id"], "")
        location_is_terminal = norm_token(location_name) in TERMINAL_LOCATION_TOKENS
        active = not state_is_terminal and not location_is_terminal
        if active:
            active_products += 1
            if not location_name:
                active_unknown_location += 1
            use_by = parse_date(product.get("use_by"))
            if use_by and use_by < as_of:
                active_expired += 1

        pack_date = parse_date(product.get("pack_date"))
        use_by = parse_date(product.get("use_by"))
        if pack_date and use_by and use_by < pack_date:
            use_by_before_pack += 1

    relation_summary = {
        "fruiting_blocks": len(fruiting_blocks),
        "fruiting_blocks_with_grain_input": sum(1 for row in fruiting_blocks if grain_rel.get(row["airtable_id"])),
        "fruiting_blocks_with_substrate_input": sum(1 for row in fruiting_blocks if substrate_rel.get(row["airtable_id"])),
        "fruiting_blocks_with_strain": sum(1 for row in fruiting_blocks if lot_strain_rel.get(row["airtable_id"])),
        "fruiting_blocks_with_output_product": sum(1 for row in fruiting_blocks if lot_product_rel.get(row["airtable_id"])),
        "products_with_origin_lot": sum(1 for row in products if product_origin_rel.get(row["airtable_id"])),
        "grain_age_at_spawn_samples": grain_age_samples,
        "grain_age_samples_with_downstream_contamination": downstream_contam_samples,
        "fruiting_blocks_with_complete_substrate_age_inputs": substrate_age_blocks,
        "grain_lots": len(grain_lots),
        "grain_lots_with_inoculation": grain_with_inoc,
        "grain_lots_contaminated": grain_self_contam,
        "grain_lots_with_inoculation_and_contamination": grain_inoc_to_contam,
        "harvest_events": len(harvest_events),
        "harvested_lots": len(harvest_lots),
        "tray_products": len(tray_products),
        "tray_products_recoverable_from_harvest_events": tray_products_recoverable,
    }

    return {
        "as_of": as_of.isoformat(),
        "rows": {
            "lots": len(lots),
            "events": len(events),
            "products": len(products),
        },
        "event_types": dict(event_types.most_common()),
        "milestone_coverage": milestone_coverage,
        "direct_event_agreement": agreement,
        "fully_colonized_event_lots": len(fully_events),
        "contaminated_event_lots": len(contam_events),
        "relations": relation_summary,
        "quality": {
            "orphan_events": len(orphan_events),
            "orphan_event_types": dict(orphan_types.most_common()),
            "undated_events": len(undated_events),
            "undated_event_types": dict(undated_types.most_common()),
            "lots_without_linked_events": lots_without_event_relation,
            "lots_without_dated_events": lots_without_dated_event,
            "lots_with_lifecycle_more_than_1_day_before_record_created": precreated_lots,
            "lots_with_lifecycle_more_than_30_days_before_record_created": precreated_30d,
            "duplicate_lot_flush_number_groups": duplicate_flush_groups,
            "harvested_lots_with_noncontiguous_flush_numbers": noncontiguous_flush_lots,
            "products_with_use_by_before_pack_date": use_by_before_pack,
        },
        "inventory": {
            "active_products_using_current_products_page_rule": active_products,
            "active_products_expired_as_of": active_expired,
            "active_products_without_storage_location": active_unknown_location,
        },
    }


def markdown(audit: dict[str, Any]) -> str:
    rows = audit["rows"]
    lines = [
        "# MushroomProcess Reporting migration audit",
        "",
        f"Inventory as-of date: `{audit['as_of']}`",
        "",
        "## Snapshot",
        "",
        f"- Lots: {rows['lots']}",
        f"- Events: {rows['events']}",
        f"- Products: {rows['products']}",
        "",
        "## Lifecycle event vocabulary",
        "",
        "| Event type | Rows |",
        "| --- | ---: |",
    ]
    for event_type, count in audit["event_types"].items():
        lines.append(f"| {event_type} | {count} |")

    lines += [
        "",
        "## Direct field / event fallback coverage",
        "",
        "| Milestone | Direct | Event | Both | Direct only | Event only | Either |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, stats in audit["milestone_coverage"].items():
        lines.append(
            f"| {name} | {stats['direct']} | {stats['event']} | {stats['both']} | "
            f"{stats['direct_only']} | {stats['event_only']} | {stats['either']} |"
        )
    lines.append(f"| fully_colonized_at (event only) | 0 | {audit['fully_colonized_event_lots']} | 0 | 0 | {audit['fully_colonized_event_lots']} | {audit['fully_colonized_event_lots']} |")
    lines.append(f"| contaminated_at (event only) | 0 | {audit['contaminated_event_lots']} | 0 | 0 | {audit['contaminated_event_lots']} | {audit['contaminated_event_lots']} |")

    r = audit["relations"]
    lines += [
        "",
        "## Relationship / analysis readiness",
        "",
        f"- Fruiting blocks with grain input: {r['fruiting_blocks_with_grain_input']}/{r['fruiting_blocks']} ({pct(r['fruiting_blocks_with_grain_input'], r['fruiting_blocks'])})",
        f"- Fruiting blocks with substrate input: {r['fruiting_blocks_with_substrate_input']}/{r['fruiting_blocks']} ({pct(r['fruiting_blocks_with_substrate_input'], r['fruiting_blocks'])})",
        f"- Fruiting blocks with strain: {r['fruiting_blocks_with_strain']}/{r['fruiting_blocks']} ({pct(r['fruiting_blocks_with_strain'], r['fruiting_blocks'])})",
        f"- Fruiting blocks with output products: {r['fruiting_blocks_with_output_product']}/{r['fruiting_blocks']} ({pct(r['fruiting_blocks_with_output_product'], r['fruiting_blocks'])})",
        f"- Products with explicit origin lot relation: {r['products_with_origin_lot']}/{rows['products']} ({pct(r['products_with_origin_lot'], rows['products'])})",
        f"- Fruiting-block grain-age-at-spawn samples: {r['grain_age_at_spawn_samples']}/{r['fruiting_blocks']} ({pct(r['grain_age_at_spawn_samples'], r['fruiting_blocks'])})",
        f"- Grain-age samples whose resulting block contaminated: {r['grain_age_samples_with_downstream_contamination']}",
        f"- Fruiting blocks with complete substrate processing-age inputs: {r['fruiting_blocks_with_complete_substrate_age_inputs']}/{r['fruiting_blocks']} ({pct(r['fruiting_blocks_with_complete_substrate_age_inputs'], r['fruiting_blocks'])})",
        f"- Grain lots with inoculation timestamp: {r['grain_lots_with_inoculation']}/{r['grain_lots']} ({pct(r['grain_lots_with_inoculation'], r['grain_lots'])})",
        f"- Grain lots with contamination event: {r['grain_lots_contaminated']}/{r['grain_lots']} ({pct(r['grain_lots_contaminated'], r['grain_lots'])})",
        f"- Harvest tray products recoverable from Harvest event product IDs: {r['tray_products_recoverable_from_harvest_events']}/{r['tray_products']} ({pct(r['tray_products_recoverable_from_harvest_events'], r['tray_products'])})",
    ]

    q = audit["quality"]
    inv = audit["inventory"]
    lines += [
        "",
        "## Historical data-quality facts",
        "",
        f"- Orphan events without a lot relation: {q['orphan_events']} ({json.dumps(q['orphan_event_types'], sort_keys=True)})",
        f"- Undated events: {q['undated_events']} ({json.dumps(q['undated_event_types'], sort_keys=True)})",
        f"- Lots without any linked event: {q['lots_without_linked_events']}",
        f"- Lots without any linked dated event: {q['lots_without_dated_events']}",
        f"- Lots whose known lifecycle begins >1 day before Airtable record creation: {q['lots_with_lifecycle_more_than_1_day_before_record_created']}",
        f"- Lots whose known lifecycle begins >30 days before Airtable record creation: {q['lots_with_lifecycle_more_than_30_days_before_record_created']}",
        f"- Duplicate lot/flush-number groups: {q['duplicate_lot_flush_number_groups']}",
        f"- Harvested lots with non-contiguous flush numbering: {q['harvested_lots_with_noncontiguous_flush_numbers']}",
        f"- Products with use_by earlier than pack_date: {q['products_with_use_by_before_pack_date']}",
        "",
        "## Inventory snapshot using the current Products-page active rule",
        "",
        f"- Active products: {inv['active_products_using_current_products_page_rule']}",
        f"- Active products expired as of {audit['as_of']}: {inv['active_products_expired_as_of']}",
        f"- Active products without a storage location: {inv['active_products_without_storage_location']}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    csv_dir = Path(args.csv_dir).expanduser().resolve()
    as_of = date.fromisoformat(args.as_of) if args.as_of else None
    try:
        audit = build_audit(csv_dir, as_of)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if args.format == "json":
        json.dump(audit, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
    else:
        sys.stdout.write(markdown(audit))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
